//汉化杂项
var cnItems = {
    'primary': '主要',
    'secondary': '次要',
    'exotic': '异国',
    'helium': '氦',
    'essence': '真髓',
    'token': '符记',
    'magma': '岩浆',
    'events': '事件',
    'repeated': '重复',
    'unique': '独特',
    'trimp': '脆皮',
    'enemy': '敌人',
    'food': '食物',
    'Food': '食物',
    'wood': '木头',
    'Wood': '木头',
    'metal': '金属',
    'Metal': '金属',
    'fragments': '碎片',
    'Fragments': '碎片',
    'gems': '宝石',
    'Gems': '宝石',
    'science': '科学',
    'Science': '科学',
    'Fire': '火焰',
    'Frost': '冰霜',
    'Wind': '风',
    'Ice': '冰',
    //传家宝
    'Magmatic Shield': '岩浆盾',
    'Magmatic Staff': '岩浆员工',
    'Legendary Staff': '传奇的员工',
    'Magnificent Shield': '华丽的盾牌',
    'Legendary Shield': '传奇的盾牌',
    'Magnificent Staff': '华丽的员工',
    'Plagued Shield': '天灾之盾',
    'Plagued Staff': '天灾之棍',
    'Epic Shield': '史诗之盾',
    'Epic Staff': '史诗之棍',
    'miner': '矿工',
    'lumber': '木料',
    'farming': '农业',
    'Poison': '毒',
    'Knowledge': '知识',
    'Condenser': '冷凝',
    'Strength': '力量',
    'Lightning': '闪电',
    'Monday': '周一',
    'Tuesday': '周二',
    'Wednesday': '周三',
    'Thursday': '周四',
    'Friday': '周五',
    'Saturday': '周六',
    'Sunday': '周日',
    'Improbability': '无序',
    'Corrupt': '腐败',
    'Penguimp': '企鹅',
    'Magma': '岩浆',
    'Healthy': '健康的',
    'Obliterated': '湮没',
    '': '',
    '': '',
    '': '',
    '': '',
    //特权
    'Agility': '敏捷',
    'Bait': '诱饵',
    'Pheromones': '信息素',
    'Packrat': '包装',
    'Motivation': '动机',
    'Power': '力量',
    'Toughness': '坚韧',
    'Looting': '掠夺',
    'Trumps': '法宝',
    'Domination': '统治',
    //从这里开始是时间传送门下的按钮
    'Discipline': '纪律',
    'Daily': '日常',
    'Metal': '金属',
    'Size': '尺寸',
    'Balance': '平衡',
    'Scientist V': '科学家 V',
    'Scientist': '科学家',
    'Looting II': '劫掠 II',
    'Carpentry II': '木工 II',
    'Power II': '力量 II',
    'Toughness II': '坚韧 II',
    'Capable': '能力',
    'Cunning': '狡猾',
    'Curious': '好奇',
    'Overkill': '超杀',
    'Resourceful': '足智多谋',
    'Coordinated': '协调',
    'Siphonology': '虹吸学',
    'Anticipation': '预期',
    'Resilience': '弹性',
    'Meditation': '冥想',
    'Relentlessness': '无情',
    'Carpentry': '木工',
    'Artisanistry': '艺术性',
    'Range': '范围',
    'Motivation II': '动机 II',
    'Meditate': '冥想',
    'Decay': '衰变',
    'Trimp': '脆皮',
    'Trapper': '捕手',
    'Electricity': '电流',
    'Frugal': '节俭',
    'Life': '生命',
    'Nom': '美味',
    'Lead': '领导',
    'Watch': '观望',
    'Mapocalypse': '地图的启示',
    'Mapology': '地图学',
    'Coordinate': '协同',
    'Crushed': '粉碎',
    'Toxicity': '毒性',
    'Devastation': '破坏',
    'Corrupted': '腐化',
    'Slow': '迟钝',
    //统计
    'Dead Trimps': '死去的脆皮',
    'Battles Won': '战斗胜利',
    'Battles Lost': '战斗失败',
    'Maps Cleared': '地图清除',
    'Zones Cleared': '区域清除',
    'Gems Collected': '宝石收集',
    'Wormholed Helium': '虫洞氦气',
    'He/Hour this Run': '本次游戏氦/小时',
    'Best He/Hr this Run': '本轮游戏中最高的氦/小时',
    'Highest Void Map Clear': '最高虚空地图清除',
    'Golden Upgrades': '黄金升级',
    'Heirlooms Found': '传家宝发现',
    'Daily Challenge Helium': '每日的挑战氦',
    'World Cells Overkilled': '超杀世界单元格敌人数量',
    'Trimps from Generator': '维度发生器生产的脆皮',
    'Nurseries Closed by Magma': '由岩浆封闭的幼儿园',
    'Zones Liquified': '区域液化',
    'Highest Zone': '最高区域',
    'Total Portals Used': '使用的总传送门',
    'Total Helium Earned': '获得总氦气',
    'Best He/Hour all Runs': '所有轮游戏中最高的氦/小时',
    'Planets Broken': '行星破碎',
    'Burned Nurseries': '燃烧的托儿所',
    'Trap/Tower Kills': '陷阱/塔杀死',
    'Gems Collected': '收集宝石',
    'Maps Cleared': '已清理地图',
    'Zones Cleared': '已清理区域',
    'Trimps Fired': '解雇的脆皮',
    'Food/Wood/Metal': '食物/木头/金属',
    'Total Void Maps Cleared': '总计清理虚空地图',
    'Tokens This Run': '本次游戏获得的令牌',
    'Amalgamators Befriended': '合并者帮助',
    'Fluffy Exp This Run': '本次游戏蓬松经验',
    'Fluffy Exp/Hr this Run': '本次游戏蓬松经验/小时',
    'Most Tokens': '令牌最高数量',
    'Best Fluffy Exp': '最高蓬松经验',
    'Best Fluffy Exp/Hr': '最高蓬松经验/小时',
    'Best Fluffy Exp/Hr this Run': '本次游戏最高蓬松经验/小时',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

};

function cnItem(text) {
    //数组里面有的，返回中文
    for (var i in cnItems) {
        if (text == i) {
            return cnItems[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cnItems) {
        if (text != i) {
            console.log("需汉化的英文Item：" + text);
            return text;
        }
    }
}



//汉化标题
var cntit = {
    'Shield': '盾',
    'Dagger': '匕首',
    'Boots': '靴子',
    'Mace': '狼牙棒',
    'Helmet': '头盔',
    'Polearm': '长柄武器',
    'Pants': '裤子',
    'Battleaxe': '战斧',
    'Shoulderguards': '护肩',
    'Greatsword': '巨剑',
    'Breastplate': '护胸甲',
    'Arbalest': '劲弩',
    'Gambeson': '夹克',
    'Trap': '陷阱',
    'Barn': '谷仓',
    'Shed': '窝棚',
    'Forge': '锻造室',
    'Hut': '茅舍',
    'House': '房子',
    'Mansion': '大厦',
    'Hotel': '旅馆',
    'Resort': '娱乐场',
    'Gateway': '出入口',
    'Wormhole': '虫洞',
    'Collector': '集电极',
    'Warpstation': '经纱站',
    'Gym': '健身房',
    'Tribute': '贡品',
    'Nursery': '托儿所',
    'Farmer': '农民',
    'Lumberjack': '伐木工',
    'Miner': '矿工',
    'Scientist': '科学家',
    'Scientists': '科学家',
    'Trainer': '培训师',
    'Trainers': '培训师',
    'Explorer': '探险家',
    'Magmamancer': '巫师',
    'Amalgamator': '合并者',
    'Fire Trimps': '解雇脆皮',
    'Gigastation': '千兆站',
    'Geneticistassist': '遗传学家助手',
    'Geneticist': '遗传学家',
    'Agility': '敏捷',
    'Bait': '诱饵',
    'Pheromones': '信息素',
    'Packrat': '包装',
    'Motivation': '动机',
    'Power': '力量',
    'Toughness': '坚韧',
    'Looting': '掠夺',
    'Trumps': '法宝',
    'Custom': '自定义',
    'Confirm Purchase': '确认购买',
    'Looting II': '劫掠 II',
    'Carpentry II': '木工 II',
    'Power II': '力量 II',
    'Toughness II': '坚韧 II',
    'Capable': '能力',
    'Cunning': '狡猾',
    'Curious': '好奇',
    'Overkill': '超杀',
    'Resourceful': '足智多谋',
    'Coordinated': '协调',
    'Coordination': '协作',
    'Siphonology': '虹吸学',
    'Anticipation': '预期',
    'Resilience': '弹性',
    'Meditation': '冥想',
    'Relentlessness': '无情',
    'Battle': '战斗',
    'Carpentry': '木工',
    'Artisanistry': '艺术性',
    'Range': '范围',
    'Motivation II': '动机 II',
    'Bloodlust': '嗜血',
    'Miners': '矿工',
    'Speedminer': '采矿加速',
    'Speedlumber': '砍伐加速',
    'Speedfarming': '耕作加速',
    'Speedscience': '研究加速',
    'Efficiency': '生产效率',
    'Megamace': '巨型狼牙棒',
    'Hellishmet': '地狱头盔',
    'Supershield': '超级盾牌',
    'Dagadder': '攻击匕首',
    'Bootboost': '增速靴',
    'Polierarm': '更长武器',
    'Pantastic': '七分裤',
    'Axeidic': '斧头',
    'Smoldershoulder': '阴燃肩',
    'Greatersword': '更大的剑',
    'Bestplate': '更好的胸甲',
    'Speedexplorer': '探险家加速',
    'Gigastation': '千兆站',
    'TrainTacular': '防御提升',
    'Potency': '繁殖效率',
    'Max': '最大',
    'AutoStorage': '自动存储',
    'AutoStructure': '自动建筑',
    'Configure AutoStructure': '自动建筑配置',
    'AutoUpgrade': '自动升级',
    'AutoPrestige': '自动重铸装备',
    'AutoGolden': '自动黄金升级',
    'Harmbalest': '伤害平衡',
    'GambesOP': '胫甲OP',
    'Maps': '地图',
    'Rename Preset': '重命名预设',
    'Portal': '传送门',
    'Pierce': '穿刺',
    'Fast': '快速',
    'Save Map Settings': '保存地图设置',
    'Reset Map Settings': '重置地图设置',
    'Recycle All': '回收所有',
    'Map Preset': '回收所有',
    'Gymystic': '健身学',
    'Shieldblock': '盾牌防御',
    'Trapstorm': '自动陷阱',
    'Blockmaster': '防御大师',
    'Decay': '衰变',
    'Show/Hide Map Config': '显示/隐藏地图设置',
    'Electricity': '电流',
    'Mastery': '专精',
    'Empowerments of Nature': '自然赋权',
    'Switch Daily': '选择日常挑战',
    'Empower': '赋能',
    'Pressure': '压力',
    'MagnetoShriek': '磁力护盾',
    'Unliving': '亡灵化',
    'Bloodthirst': '嗜血',
    'Scryer Formation': '占卜者阵型',
    'Fire Trap': '火焰陷阱',
    'Frost Trap': '冰霜陷阱',
    'Shift Up': '上移',
    'Shift Down': '下移',
    'Sell Trap/Tower': '出售陷阱/塔',
    'Queue': '队列',
    'Biome': '生物群落',
    'Size': '尺寸',
    'Loot': '抢劫',
    'Special Modifier': '特殊修饰符',
    'Extra Zones': '额外区域',
    'Difficulty': '难度',
    'Perfect Sliders': '完美的滑块',
    'Enchanted Gardens': '魔法花园',
    'Repeat Map': '重复地图',
    'Heirloom': '传家宝',
    'Trustworthy Trimps': '守信的脆皮',
    'World Info': '世界信息',
    'AutoGold': '自动黄金',
    'Threat': '威胁',
    'Enemies': '敌人',
    'Runestones': '符石',
    'Spirestones': '尖顶石头',
    'Trimps Per Second': '每秒脆皮',
    'Max Trimps': '脆皮上限',
    'Scryhard I': '努力占卜 I',
    'Scryhard II': '努力占卜 II',
    'AutoJobs': '自动工作',
    'Legs for Days': '天残脚',
    'Explorer Aura I': '探险家光环 I',
    'Explorer Aura II': '探险家光环 II',
    'Respec Masteries': '洗点',
    'Configure Maps': '配置地图',
    'Map at Spires': '尖塔地图',
    'Import Perk Preset': '导入Perk预设',
    'Export Perk Setup': '导出Perk设置',
    //专精
    'Bionic Magnet I': '仿生磁 I',
    'Bionic Magnet II': '仿生磁 II',
    'Portal Generator': '传送门生成器',
    'Bounty Hunter': '赏金猎人',
    'Home Detector': '家庭探测器',
    'Turkimp Tamer I': '驯兽师 I',
    'Turkimp Tamer II': '驯兽师 II',
    'Turkimp Tamer III': '驯兽师 III',
    'Turkimp Tamer IV': '驯兽师 IV',
    'Void Power I': '虚空力量 I',
    'Void Power II': '虚空力量 II',
    'Void Power III': '虚空力量 III',
    'Metallic Coat': '金属外套',
    'Headstart I': '领先地位 I',
    'Headstart II': '领先地位 II',
    'Headstart III': '领先地位 III',
    'Foremany': '脱颖而出',
    'Map Reducer I': '地图还原剂 I',
    'Map Reducer II': '地图还原剂 II',
    'Double Build': '双重建造',
    'King of Bones I': '骨头之王 I',
    'King of Bones II': '骨头之王 II',
    'Hyperspeed I': '超高速 I',
    'Hyperspeed II': '超高速 II',
    'Blacksmithery I': '黑煅炼 I',
    'Blacksmithery II': '黑煅炼 II',
    'Blacksmithery III': '黑煅炼 III',
    'Quick Gen': '快速第二代',
    'AutoStructure': '自动结构',
    'Magma Flow': '岩浆流',
    'Natural Diplomacy I': '自然外交 I',
    'Natural Diplomacy II': '自然外交 II',
    'Natural Diplomacy III': '自然外交 III',
    'Liquification I': '液化 I',
    'Liquification II': '液化 II',
    'Magmamancermancy': '大巫师',
    'Patience': '忍耐',
    'Still Rowing I': '持续赛艇 I',
    'Still Rowing II': '持续赛艇 II',
    'Strength in Health': '生命的力量',
    'Void Specialization I': '虚空专精 I',
    'Void Specialization II': '虚空专精 II',
    'Megascience':'超级科学',
    'Magmamancers':'岩浆魔法师',
    'Megafarming':'大型农业',
    'Condenser Tower':'冷凝塔',
    'Condenser Tower II':'冷凝塔 II',
    'Knowledge Tower':'知识塔',
    'Knowledge Tower II':'知识塔 II',
    'Poison Trap':'毒物陷阱',
    'Poison Trap II':'毒物陷阱 II',
    'Megaminer':'超级矿工',
    'Lightning Trap':'闪电陷阱',
    'Lightning Trap II':'闪电陷阱 II',
    'Frost Trap IV':'冰霜陷阱 IV',
    'Strength Tower':'力量塔',
    'Strength Tower II':'力量塔 II',
    'Strength Tower III':'力量塔 III',
    'Fire Trap III':'火焰陷阱 III',
    'Trap Layout 1':'陷阱布局 1',
    'Trap Layout 2':'陷阱布局 2',
    'Configure AutoJobs':'配置自动工作',
    'Configure Generator State':'配置生成器状态',
    'Spire Settings':'尖塔设置',
    'Well Fed':'吃的很饱',
    'Fluffy':'蓬松',
    'UberHotel':'优步酒店',
    'UberMansion':'优步',
    'UberResort':'优步娱乐场',
    'No Map At Zone':'区域没有地图',
    'UberHouse':'优步房子',
    'UberHut':'优步茅舍',
    'Map Corruption':'地图腐化',
    'Food/Wood/Metal Loot Breakdown':'食物/木头/金属 洗劫一空',
    'Breezy':'活泼的',
    'Deca Build':'十进制构建',
    'Amalgagreater':'融合器',
    'Flufffocus':'蓬松焦点',
    'Excessive':'过度',
    'Flufffinity':'蓬松有限性',
    'Charged Crits':'带电暴击',
    'Confirm Respec Masteries':'确认专精洗点',
    //成就
    'Maptain':'地图符号',
    "What's This For?":'这个是干什么的?',
    'Collector of Shinies':'闪亮的收藏家',
    'Dragimp Lover':'Dragimp爱人',
    'Expert of Shinies':'闪亮的专家',
    'Jeweller':'珠宝商',
    'Gemaster':'宝石大师',
    'Feats':'专长',
    'Speed: The Block':'速度: 障碍区',
    'Speed: The Wall':'速度: 高墙',
    'Speed: Anger':'速度: 愤怒维度',
    'Speed: Doom':'速度: 末日神殿',
    'Speed: The Prison':'速度: 监狱',
    'Speed: Bionic':'速度: 仿生仙境',
    'Speed: Star':'速度: 爆炸之星',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    'Frigid':'寒冷',
    'Angry Racer':'愤怒的赛车手',
    'Gallop to Doom':'奔向末日',
    'Canter to Doom':'注定失败',
    'Map Destroyer':'地图毁灭者',
    'Centennial Trimper':'百年修剪者',
    'Prison Sprint':'监狱冲刺',
    'Prison Road Trip':'监狱之旅',
    'Frozen':'冻结',
    'Hour Bender':'小时狂欢',
    'Daylusional':'白天的',
    'Chilly':'寒意',
    'Frosty':'寒霜',
    'Cool':'凉爽',
    'Coldlector':'冷冻机',
    'Expert':'能手',
    'Sitter':'坐着',
    'Gelid':'文件',
    'Amnesia':'健忘症',
    'Savior':'救世主',
    'Connoisseur':'行家',
    'Vacuum':'真空',
    'Aficionado':'业余',
    'Daystroyer':'日托',
    'Seeker':'探求者',
    'Fancier':'爱好者',
    'Adventurer':'冒险家',
    'GigaClearer':'千兆清理者',
    'Coddler':'小贩',
    'Pathfinder':'探路者',
    'Centelium':'中心',
    'Prison Trek':'监狱旅行',
    'Guardian':'守护者',
    'Dayrailed':'日日的',
    'Daylighted':'日光',
    'Cartographer':'制图师',
    'Map Maker':'地图绘制者',
    'Map Annihilator':'地图歼灭者',
    'Map Runner':'地图奔跑者',
    'Curator':'监护人',
    'Caretaker':'看管者',
    'Accumulator':'蓄电池',
    'Nanny':'保姆',
    'Daypocalyptic':'消日剂',
    'When The Wild Things Are':'当疯狂的事',
    'Advocate':'支持者',
    'Glacial':'冰河',
    'Vanquisher':'征服者',
    'Globetrotter':'周游世界',
    'Supervisor':'监督者',
    'Daystiny':'白昼的',
    'Crisp':'易碎',
    'Pioneer':'拓荒者',
    'Prison Tour':'监狱巡视路线',
    'Wall Student':'墙上的学生',
    'Wall Scaler':'墙壁标尺',
    'Prison Hike':'监狱远足',
    'Block Professional':'专业技术人员',
    'Daydicated':'走神的',
    'Prison Hike':'监狱徒步旅行',
    'Acquired Frost':'后天霜冻',
    'Time of Your Life':'你生命中的时光',
    'Brisk':'轻快',
    'A Trimp Through Time':'一个脆皮穿越时空',
    'Quick N Cool':'快速冷却',
    'Frosty Tanker':'结霜油船',
    'Trot to Doom':'快步走向末日',
    'Angry Teleporter':'愤怒传送者',
    'Angry Sprinter':'愤怒的运动员',
    'Daytermined':'白昼终结',
    'Venti Timeachino':'超大时间',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    //阻止页面打印
    '自动战斗':'自动战斗',
    '战斗':'战斗',
    '世界信息':'世界信息',
    '守信的脆皮':'守信的脆皮',
    '购买最大':'购买最大',
    '攻击阵型':'攻击阵型',
    '防守阵型':'防守阵型',
    '肉山阵型':'肉山阵型',
    '无编队':'无编队',
    '退出地图':'退出地图',
    '重复10次':'重复10次',
    '装备优先':'装备优先',
    '脆皮信息':'脆皮信息',
    
};

function cntitle(text) {
    //数组里面有的，返回中文
    for (var i in cntit) {
        if (text == i) {
            return cntit[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cntit) {
        if (text != i) {
            console.log("需汉化的英文标题：" + text);
            return text;
        }
    }
}

//汉化地图名
var cnmaps = {
    'Dimension of Anger': '愤怒维度',
    'The Prison': '监狱',
    'Bionic Wonderland': '仿生仙境',
    'Bionic Wonderland X': '仿生仙境X',
    'Bionic Wonderland IX': '仿生仙境IX',
    'Bionic Wonderland XI': '仿生仙境XI',
    'The Block': '障碍区',
    'The Wall': '高墙',
    'Trimple Of Doom': '末日之神殿',
    'Imploding Star': '爆炸之星',
    'Tricky Paradise': '整蛊天堂',
    'Haunted Gardens': '闹鬼花园',
    'Whispering Gardens': '耳语花园',
    'Abandoned Gardens': '被遗弃的花园',
    'Bewitched Gardens': '迷人的花园',
    'Terrible Gardens': '可怕的花园',
    'Dark Gardens': '黑暗花园',
    'Blighted Gardens': '枯萎的花园',
    'Sacred Gardens': '神圣花园',
    'Weird Gardens': '怪异的花园',
    'Steamy Gardens': '蒸汽花园',
    'Red Gardens': '红色花园',
    'Calm Gardens': '平静的花园',
    'Evil Gardens': '邪恶花园',
    'Dry Gardens': '干燥的花园',
    'Enchanted Gardens': '魔法花园',
    'Light Gardens': '光明花园',
    'Dirty Gardens': '肮脏的花园',
    'Fiery Gardens': '火热的花园',
    'Deadly Void': '致命的虚空',
    'Heinous Void': '令人发指的虚空',
    'Heinous Pit': '令人发指的坑',
    'Heinous Nightmare': '令人发指的梦魇',
    'Heinous Descent': '令人发指的血统',
    'Poisonous Void': '有毒虚空',
    'Poisonous Pit': '毒坑',
    'Poisonous Nightmare': '有毒的噩梦',
    'Poisonous Descent': '有毒的血统',
    'Deadly Pit': '致命的坑',
    'Deadly Descent': '致命的血统',
    'Destructive Descent': '破坏性的血统',
    'Destructive Nightmare': '破坏性的噩梦',
    'Destructive Void': '破坏性虚空',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
};

function cnmap(text) {
    //数组里面有的，返回中文
    for (var i in cnmaps) {
        if (text == i) {
            return cnmaps[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cnmaps) {
        if (text != i) {
            console.log("需汉化的英文地图名：" + text);
            return text;
        }
    }
}
