//汉化标题
var cntit = {
    'Shield': '盾',
    'Dagger': '匕首',
    'Boots': '靴子',
    'Mace': '狼牙棒',
    'Helmet': '头盔',
    'Polearm': '长柄武器',
    'Pants': '裤子',
    'Battleaxe': '战斧',
    'Shoulderguards': '护肩',
    'Greatsword': '巨剑',
    'Breastplate': '护胸甲',
    'Arbalest': '劲弩',
    'Gambeson': '夹克',
    'Trap': '陷阱',
    'Barn': '谷仓',
    'Shed': '窝棚',
    'Forge': '锻造室',
    'Hut': '茅舍',
    'House': '房子',
    'Mansion': '大厦',
    'Hotel': '旅馆',
    'Resort': '娱乐场',
    'Gateway': '出入口',
    'Wormhole': '虫洞',
    'Collector': '集电极',
    'Warpstation': '经纱站',
    'Gym': '健身房',
    'Tribute': '贡品',
    'Nursery': '托儿所',
    'Farmer': '农民',
    'Lumberjack': '伐木工',
    'Miner': '矿工',
    'Scientist': '科学家',
    'Scientists': '科学家',
    'Trainer': '培训师',
    'Trainers': '培训师',
    'Explorer': '探险家',
    'Magmamancer': '巫师',
    'Amalgamator': '合并者',
    'Fire Trimps': '解雇脆皮',
    'Gigastation': '千兆站',
    'Geneticistassist': '遗传学家助手',
    'Geneticist': '遗传学家',
    'Agility': '敏捷',
    'Bait': '诱饵',
    'Pheromones': '信息素',
    'Packrat': '包装',
    'Motivation': '动机',
    'Power': '力量',
    'Toughness': '坚韧',
    'Looting': '掠夺',
    'Trumps': '法宝',
    'Custom': '自定义',
    'Confirm Purchase': '确认购买',
    'Looting II': '劫掠 II',
    'Carpentry II': '木工 II',
    'Power II': '力量 II',
    'Toughness II': '坚韧 II',
    'Capable': '能力',
    'Cunning': '狡猾',
    'Curious': '好奇',
    'Overkill': '超杀',
    'Resourceful': '足智多谋',
    'Coordinated': '协调',
    'Coordination': '协作',
    'Siphonology': '虹吸学',
    'Anticipation': '预期',
    'Resilience': '弹性',
    'Meditation': '冥想',
    'Relentlessness': '无情',
    'Battle': '战斗',
    'Carpentry': '木工',
    'Artisanistry': '艺术性',
    'Range': '范围',
    'Motivation II': '动机 II',
    'Bloodlust': '嗜血',
    'Miners': '矿工',
    'Speedminer': '采矿加速',
    'Speedlumber': '砍伐加速',
    'Speedfarming': '耕作加速',
    'Speedscience': '研究加速',
    'Efficiency': '生产效率',
    'Megamace': '巨型狼牙棒',
    'Hellishmet': '地狱头盔',
    'Supershield': '超级盾牌',
    'Dagadder': '攻击匕首',
    'Bootboost': '增速靴',
    'Polierarm': '更长武器',
    'Pantastic': '七分裤',
    'Axeidic': '斧头',
    'Smoldershoulder': '阴燃肩',
    'Greatersword': '更大的剑',
    'Bestplate': '更好的胸甲',
    'Speedexplorer': '探险家加速',
    'Gigastation': '千兆站',
    'TrainTacular': '防御提升',
    'Potency': '繁殖效率',
    'Max': '最大',
    'AutoStorage': '自动存储',
    'AutoStructure': '自动建筑',
    'Configure AutoStructure': '自动建筑配置',
    'AutoUpgrade': '自动升级',
    'AutoPrestige': '自动重铸装备',
    'AutoGolden': '自动黄金升级',
    'Harmbalest': '伤害平衡',
    'GambesOP': '胫甲OP',
    'Maps': '地图',
    'Rename Preset': '重命名预设',
    'Portal': '传送门',
    'Pierce': '穿刺',
    'Fast': '快速',
    'Save Map Settings': '保存地图设置',
    'Reset Map Settings': '重置地图设置',
    'Recycle All': '回收所有',
    'Map Preset': '回收所有',
    'Gymystic': '健身学',
    'Shieldblock': '盾牌防御',
    'Trapstorm': '自动陷阱',
    'Blockmaster': '防御大师',
    'Decay': '衰变',
    'Show/Hide Map Config': '显示/隐藏地图设置',
    'Electricity': '电流',
    'Mastery': '专精',
    'Empowerments of Nature': '自然赋权',
    'Switch Daily': '选择日常挑战',
    'Empower': '赋能',
    'Pressure': '压力',
    'MagnetoShriek': '磁力护盾',
    'Unliving': '亡灵化',
    'Bloodthirst': '嗜血',
    'Scryer Formation': '占卜者阵型',
    'Fire Trap': '火焰陷阱',
    'Frost Trap': '冰霜陷阱',
    'Shift Up': '上移',
    'Shift Down': '下移',
    'Sell Trap/Tower': '出售陷阱/塔',
    'Queue': '队列',
    'Biome': '生物群落',
    'Size': '尺寸',
    'Loot': '抢劫',
    'Special Modifier': '特殊修饰符',
    'Extra Zones': '额外区域',
    'Difficulty': '难度',
    'Perfect Sliders': '完美的滑块',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
};

function cntitle(text) {
    //数组里面有的，返回中文
    for (var i in cntit) {
        if (text == i) {
            return cntit[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cntit) {
        if (text != i) {
            console.log("需汉化的标题英文：" + text);
            return text;
        }
    }
}

//汉化地图名
var cnmaps = {
    'Dimension of Anger': '愤怒维度',
    'The Prison': '监狱',
    'Bionic Wonderland': '仿生仙境',
    'The Block': '障碍区',
    'The Wall': '高墙',
    'Trimple Of Doom': '末日之神殿',
    'Imploding Star': '爆炸之星',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
};

function cnmap(text) {
    //数组里面有的，返回中文
    for (var i in cnmaps) {
        if (text == i) {
            return cnmaps[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cnmaps) {
        if (text != i) {
            console.log("需汉化的英文地图名："+text);
            return text;
        }
    }
}
