/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'primary': '主要',
    'secondary': '次要',
    'exotic': '异国',
    'helium': '氦',
    'essence': '真髓',
    'token': '符记',
    'magma': '岩浆',
    'events': '事件',
    'repeated': '重复',
    'unique': '独特',
    'trimp': '脆皮',
    'enemy': '敌人',
    'food': '食物',
    'Food': '食物',
    'wood': '木头',
    'Wood': '木头',
    'metal': '金属',
    'Metal': '金属',
    'fragments': '碎片',
    'Fragments': '碎片',
    'gems': '宝石',
    'Gems': '宝石',
    'science': '科学',
    'Science': '科学',
    'Fire': '火焰',
    'Frost': '冰霜',
    'Wind': '风',
    'Ice': '冰',
    //传家宝
    'Magmatic Shield': '岩浆盾',
    'Magmatic Staff': '岩浆员工',
    'Legendary Staff': '传奇的员工',
    'Magnificent Shield': '华丽的盾牌',
    'Legendary Shield': '传奇的盾牌',
    'Magnificent Staff': '华丽的员工',
    'Plagued Shield': '天灾之盾',
    'Plagued Staff': '天灾之棍',
    'Epic Shield': '史诗之盾',
    'Epic Staff': '史诗之棍',
    'miner': '矿工',
    'lumber': '木料',
    'farming': '农业',
    'Poison': '毒',
    'Knowledge': '知识',
    'Condenser': '冷凝',
    'Strength': '力量',
    'Lightning': '闪电',
    'Monday': '周一',
    'Tuesday': '周二',
    'Wednesday': '周三',
    'Thursday': '周四',
    'Friday': '周五',
    'Saturday': '周六',
    'Sunday': '周日',
    'Improbability': '无序',
    'Corrupt': '腐败',
    'Penguimp': '企鹅',
    'Magma': '岩浆',
    'Healthy': '健康的',
    'Obliterated': '湮没',
    'Common Core': '共同核心',
    'Rare Core': '稀有核心',
    'Uncommon Core': '罕见核心',
    'Nullifium': '虚空物质',
    'Nu': '虚空物质',
    '': '',
    //传家宝效果
    'Condenser Effect': '冷凝器效果',
    'Runestone Drop Rate': '符石掉率',
    'Fire Trap Damage': '火焰陷阱的伤害',
    'Poison Trap Damage': '毒陷阱的伤害',
    'Lightning Trap Damage': '光陷阱的伤害',
    'Fluffy Exp': '蓬松经验',
    'Plaguebringer': '瘟疫传播',
    'Strength Tower Effect': '力量塔效果',
    'Ss': '尖塔石头',
    '': '',
    '': '',
    '': '',
    '': '',
    //特权
    'Agility': '敏捷',
    'Bait': '诱饵',
    'Pheromones': '信息素',
    'Packrat': '包装',
    'Motivation': '动机',
    'Power': '力量',
    'Toughness': '坚韧',
    'Looting': '掠夺',
    'Trumps': '法宝',
    'Domination': '统治',
    //从这里开始是时间传送门下的按钮
    'Discipline': '纪律',
    'Daily': '日常',
    'Metal': '金属',
    'Size': '尺寸',
    'Balance': '平衡',
    'Scientist V': '科学家 V',
    'Scientist': '科学家',
    'Looting II': '劫掠 II',
    'Carpentry II': '木工 II',
    'Power II': '力量 II',
    'Toughness II': '坚韧 II',
    'Capable': '能力',
    'Cunning': '狡猾',
    'Curious': '好奇',
    'Overkill': '超杀',
    'Resourceful': '足智多谋',
    'Coordinated': '协调',
    'Siphonology': '虹吸学',
    'Anticipation': '预期',
    'Resilience': '弹性',
    'Meditation': '冥想',
    'Relentlessness': '无情',
    'Carpentry': '木工',
    'Artisanistry': '艺术性',
    'Range': '范围',
    'Motivation II': '动机 II',
    'Meditate': '冥想',
    'Decay': '衰变',
    'Trimp': '脆皮',
    'Trapper': '捕手',
    'Electricity': '电流',
    'Frugal': '节俭',
    'Life': '生命',
    'Nom': '美味',
    'Lead': '领导',
    'Watch': '观望',
    'Mapocalypse': '地图的启示',
    'Mapology': '地图学',
    'Coordinate': '协同',
    'Crushed': '粉碎',
    'Toxicity': '毒性',
    'Devastation': '破坏',
    'Corrupted': '腐化',
    'Slow': '迟钝',
    //统计
    'Dead Trimps': '死去的脆皮',
    'Battles Won': '战斗胜利',
    'Battles Lost': '战斗失败',
    'Maps Cleared': '地图清除',
    'Zones Cleared': '区域清除',
    'Gems Collected': '宝石收集',
    'Wormholed Helium': '虫洞氦气',
    'He/Hour this Run': '本次游戏氦/小时',
    'Best He/Hr this Run': '本轮游戏中最高的氦/小时',
    'Highest Void Map Clear': '最高虚空地图清除',
    'Golden Upgrades': '黄金升级',
    'Heirlooms Found': '传家宝发现',
    'Daily Challenge Helium': '每日的挑战氦',
    'World Cells Overkilled': '超杀世界单元格敌人数量',
    'Trimps from Generator': '维度发生器生产的脆皮',
    'Nurseries Closed by Magma': '由岩浆封闭的幼儿园',
    'Zones Liquified': '区域液化',
    'Highest Zone': '最高区域',
    'Total Portals Used': '使用的总传送门',
    'Total Helium Earned': '获得总氦气',
    'Best He/Hour all Runs': '所有轮游戏中最高的氦/小时',
    'Planets Broken': '行星破碎',
    'Burned Nurseries': '燃烧的托儿所',
    'Trap/Tower Kills': '陷阱/塔杀死',
    'Gems Collected': '收集宝石',
    'Maps Cleared': '已清理地图',
    'Zones Cleared': '已清理区域',
    'Trimps Fired': '解雇的脆皮',
    'Food/Wood/Metal': '食物/木头/金属',
    'Total Void Maps Cleared': '总计清理虚空地图',
    'Tokens This Run': '本次游戏获得的符记',
    'Amalgamators Befriended': '合并者帮助',
    'Fluffy Exp This Run': '本次游戏蓬松经验',
    'Fluffy Exp/Hr this Run': '本次游戏蓬松经验/小时',
    'Most Tokens': '符记最高数量',
    'Best Fluffy Exp': '最高蓬松经验',
    'Best Fluffy Exp/Hr': '最高蓬松经验/小时',
    'Best Fluffy Exp/Hr this Run': '本次游戏最高蓬松经验/小时',
    'cache': '缓存',
    'bone': '骨头',
    'Classy': '经典',
    //汉化维度发生器升级标题
    'Efficiency': '效率',
    'Capacity': '容量',
    'Supply': '供给',
    'Overclocker': '超频',
    'Hybridization': '混合',
    'Storage': '存储',
    'Shielding': '屏障',
    'Slowburn': '缓慢燃烧',
    'Supervision': '管理',
    'Simulacrum': '复制',
    'Trap': '陷阱',
    'Barn': '谷仓',
    'Shed': '窝棚',
    'Forge': '锻造室',
    'Hut': '茅舍',
    'House': '房子',
    'Mansion': '大厦',
    'Hotel': '旅馆',
    'Resort': '娱乐场',
    'Gateway': '出入口',
    'Wormhole': '虫洞',
    'Collector': '集电极',
    'Warpstation': '经纱站',
    'Gym': '健身房',
    'Tribute': '贡品',
    'Nursery': '托儿所',
    'Loot': '战利品',
    'Unlocks': '解锁',
    'Combat': '战斗',
    'enabled': '启用',
    //修饰符
    'Fast Attacks': '快速攻击',
    'Large Cache': '大缓存',
    'Huge Cache': '巨大缓存',
    'Small Savory Cache': '小美味缓存',
    'Small Wooden Cache': '小木制缓存',
    'Small Metal Cache': '小金属缓存',
    'Large Savory Cache': '大美味缓存',
    'Large Wooden Cache': '大木制缓存',
    'Large Metal Cache': '大属缓存',
    'Prestigious': '声望',
    'Legendary': '传奇',
    'Magnificent': '史诗',
    'Magmatic': '岩浆',
    'Ethereal': '暗金',
    'Story': '故事',
    '': '',
    '': '',
    '': '',
    //1.2.标题
    'Shield': '盾',
    'Dagger': '匕首',
    'Boots': '靴子',
    'Mace': '狼牙棒',
    'Helmet': '头盔',
    'Polearm': '长柄武器',
    'Pants': '裤子',
    'Battleaxe': '战斧',
    'Shoulderguards': '护肩',
    'Greatsword': '巨剑',
    'Breastplate': '护胸甲',
    'Arbalest': '劲弩',
    'Gambeson': '夹克',
    'Trap': '陷阱',
    'Barn': '谷仓',
    'Shed': '窝棚',
    'Forge': '锻造室',
    'Hut': '茅舍',
    'House': '房子',
    'Mansion': '大厦',
    'Hotel': '旅馆',
    'Resort': '娱乐场',
    'Gateway': '出入口',
    'Wormhole': '虫洞',
    'Collector': '集电极',
    'Warpstation': '经纱站',
    'Gym': '健身房',
    'Tribute': '贡品',
    'Nursery': '托儿所',
    'Farmer': '农民',
    'Lumberjack': '伐木工',
    'Miner': '矿工',
    'Scientist': '科学家',
    'Scientists': '科学家',
    'Trainer': '培训师',
    'Trainers': '培训师',
    'Explorer': '探险家',
    'Magmamancer': '巫师',
    'Amalgamator': '合并者',
    'Fire Trimps': '解雇脆皮',
    'Gigastation': '千兆站',
    'Geneticistassist': '遗传学家助手',
    'Geneticist': '遗传学家',
    'Agility': '敏捷',
    'Bait': '诱饵',
    'Pheromones': '信息素',
    'Packrat': '包装',
    'Motivation': '动机',
    'Power': '力量',
    'Toughness': '坚韧',
    'Looting': '掠夺',
    'Trumps': '法宝',
    'Custom': '自定义',
    'Confirm Purchase': '确认购买',
    'Looting II': '劫掠 II',
    'Carpentry II': '木工 II',
    'Power II': '力量 II',
    'Toughness II': '坚韧 II',
    'Capable': '能力',
    'Cunning': '狡猾',
    'Curious': '好奇',
    'Overkill': '超杀',
    'Resourceful': '足智多谋',
    'Coordinated': '协调',
    'Coordination': '协作',
    'Siphonology': '虹吸学',
    'Anticipation': '预期',
    'Resilience': '弹性',
    'Meditation': '冥想',
    'Relentlessness': '无情',
    'Battle': '战斗',
    'Carpentry': '木工',
    'Artisanistry': '艺术性',
    'Range': '范围',
    'Motivation II': '动机 II',
    'Bloodlust': '嗜血',
    'Miners': '矿工',
    'Speedminer': '采矿加速',
    'Speedlumber': '砍伐加速',
    'Speedfarming': '耕作加速',
    'Speedscience': '研究加速',
    'Efficiency': '生产效率',
    'Megamace': '巨型狼牙棒',
    'Hellishmet': '地狱头盔',
    'Supershield': '超级盾牌',
    'Dagadder': '攻击匕首',
    'Bootboost': '增速靴',
    'Polierarm': '更长武器',
    'Pantastic': '七分裤',
    'Axeidic': '斧头',
    'Smoldershoulder': '阴燃肩',
    'Greatersword': '更大的剑',
    'Bestplate': '更好的胸甲',
    'Speedexplorer': '探险家加速',
    'Gigastation': '千兆站',
    'TrainTacular': '防御提升',
    'Potency': '繁殖效率',
    'Max': '最大',
    'AutoStorage': '自动存储',
    'AutoStructure': '自动建筑',
    'Configure AutoStructure': '自动建筑配置',
    'AutoUpgrade': '自动升级',
    'AutoPrestige': '自动重铸装备',
    'AutoGolden': '自动黄金升级',
    'Harmbalest': '伤害平衡',
    'GambesOP': '胫甲OP',
    'Maps': '地图',
    'Rename Preset': '重命名预设',
    'Portal': '传送门',
    'Pierce': '穿刺',
    'Fast': '快速',
    'Save Map Settings': '保存地图设置',
    'Reset Map Settings': '重置地图设置',
    'Recycle All': '回收所有',
    'Map Preset': '回收所有',
    'Gymystic': '健身学',
    'Shieldblock': '盾牌防御',
    'Trapstorm': '自动陷阱',
    'Blockmaster': '防御大师',
    'Decay': '衰变',
    'Show/Hide Map Config': '显示/隐藏地图设置',
    'Electricity': '电流',
    'Mastery': '专精',
    'Empowerments of Nature': '自然赋权',
    'Switch Daily': '选择日常挑战',
    'Empower': '赋能',
    'Pressure': '压力',
    'MagnetoShriek': '磁力护盾',
    'Unliving': '亡灵化',
    'Bloodthirst': '嗜血',
    'Scryer Formation': '占卜者阵型',
    'Fire Trap': '火焰陷阱',
    'Frost Trap': '冰霜陷阱',
    'Shift Up': '后移',
    'Shift Down': '前移',
    'Sell Trap/Tower': '出售陷阱/塔',
    'Queue': '队列',
    'Biome': '生物群落',
    'Size': '尺寸',
    'Loot': '抢劫',
    'Special Modifier': '特殊修饰符',
    'Extra Zones': '额外区域',
    'Difficulty': '难度',
    'Perfect Sliders': '完美的滑块',
    'Enchanted Gardens': '魔法花园',
    'Repeat Map': '重复地图',
    'Heirloom': '传家宝',
    'Trustworthy Trimps': '守信的脆皮',
    'World Info': '世界信息',
    'AutoGold': '自动黄金',
    'Threat': '威胁',
    'Enemies': '敌人',
    'Runestones': '符石',
    'Spirestones': '尖塔石头',
    'Trimps Per Second': '每秒脆皮',
    'Max Trimps': '脆皮上限',
    'Scryhard I': '努力占卜 I',
    'Scryhard II': '努力占卜 II',
    'AutoJobs': '自动工作',
    'Legs for Days': '天残脚',
    'Explorer Aura I': '探险家光环 I',
    'Explorer Aura II': '探险家光环 II',
    'Respec Masteries': '洗点',
    'Configure Maps': '配置地图',
    'Map at Spires': '尖塔地图',
    'Import Perk Preset': '导入Perk预设',
    'Export Perk Setup': '导出Perk设置',
    //专精
    'Bionic Magnet I': '仿生磁 I',
    'Bionic Magnet II': '仿生磁 II',
    'Portal Generator': '传送门生成器',
    'Bounty Hunter': '赏金猎人',
    'Home Detector': '家庭探测器',
    'Turkimp Tamer I': '驯兽师 I',
    'Turkimp Tamer II': '驯兽师 II',
    'Turkimp Tamer III': '驯兽师 III',
    'Turkimp Tamer IV': '驯兽师 IV',
    'Void Power I': '虚空力量 I',
    'Void Power II': '虚空力量 II',
    'Void Power III': '虚空力量 III',
    'Metallic Coat': '金属外套',
    'Headstart I': '领先地位 I',
    'Headstart II': '领先地位 II',
    'Headstart III': '领先地位 III',
    'Foremany': '脱颖而出',
    'Map Reducer I': '地图还原剂 I',
    'Map Reducer II': '地图还原剂 II',
    'Double Build': '双重建造',
    'King of Bones I': '骨头之王 I',
    'King of Bones II': '骨头之王 II',
    'Hyperspeed I': '超高速 I',
    'Hyperspeed II': '超高速 II',
    'Blacksmithery I': '黑煅炼 I',
    'Blacksmithery II': '黑煅炼 II',
    'Blacksmithery III': '黑煅炼 III',
    'Quick Gen': '快速第二代',
    'AutoStructure': '自动结构',
    'Magma Flow': '岩浆流',
    'Natural Diplomacy I': '自然外交 I',
    'Natural Diplomacy II': '自然外交 II',
    'Natural Diplomacy III': '自然外交 III',
    'Liquification I': '液化 I',
    'Liquification II': '液化 II',
    'Magmamancermancy': '大巫师',
    'Patience': '忍耐',
    'Still Rowing I': '持续赛艇 I',
    'Still Rowing II': '持续赛艇 II',
    'Strength in Health': '生命的力量',
    'Void Specialization I': '虚空专精 I',
    'Void Specialization II': '虚空专精 II',
    'Megascience': '超级科学',
    'Magmamancers': '岩浆魔法师',
    'Megafarming': '大型农业',
    'Condenser Tower': '冷凝塔',
    'Condenser Tower II': '冷凝塔 II',
    'Knowledge Tower': '知识塔',
    'Knowledge Tower II': '知识塔 II',
    'Poison Trap': '毒物陷阱',
    'Poison Trap II': '毒物陷阱 II',
    'Megaminer': '超级矿工',
    'Lightning Trap': '闪电陷阱',
    'Lightning Trap II': '闪电陷阱 II',
    'Frost Trap IV': '冰霜陷阱 IV',
    'Strength Tower': '力量之塔',
    'Strength Tower II': '力量之塔 II',
    'Strength Tower III': '力量之塔 III',
    'Fire Trap III': '火焰陷阱 III',
    'Trap Layout 1': '陷阱布局 1',
    'Trap Layout 2': '陷阱布局 2',
    'Configure AutoJobs': '配置自动工作',
    'Configure Generator State': '配置生成器状态',
    'Spire Settings': '尖塔设置',
    'Well Fed': '吃的很饱',
    'Fluffy': '蓬松',
    'UberHotel': '优步酒店',
    'UberMansion': '优步',
    'UberResort': '优步娱乐场',
    'No Map At Zone': '区域没有地图',
    'UberHouse': '优步房子',
    'UberHut': '优步茅舍',
    'Map Corruption': '地图腐化',
    'Food/Wood/Metal Loot Breakdown': '食物/木头/金属 洗劫一空',
    'Breezy': '活泼的',
    'Deca Build': '十进制构建',
    'Amalgagreater': '融合器',
    'Flufffocus': '蓬松焦点',
    'Excessive': '过度',
    'Flufffinity': '蓬松有限性',
    'Charged Crits': '带电暴击',
    'Confirm Respec Masteries': '确认专精洗点',
    //成就
    'Maptain': '地图符号',
    "What's This For?": '这个是干什么的?',
    'Collector of Shinies': '闪亮的收藏家',
    'Dragimp Lover': 'Dragimp爱人',
    'Expert of Shinies': '闪亮的专家',
    'Jeweller': '珠宝商',
    'Gemaster': '宝石大师',
    'Feats': '专长',
    'Speed: The Block': '速度: 障碍区',
    'Speed: The Wall': '速度: 高墙',
    'Speed: Anger': '速度: 愤怒维度',
    'Speed: Doom': '速度: 末日神殿',
    'Speed: The Prison': '速度: 监狱',
    'Speed: Bionic': '速度: 仿生仙境',
    'Speed: Star': '速度: 爆炸之星',
    'Frigid': '寒冷',
    'Gallop to Doom': '奔向末日',
    'Canter to Doom': '注定失败',
    'Walk to Doom': '走到末日',
    'Trot to Doom': '快步走向末日',
    'Map Destroyer': '地图毁灭者',
    'Centennial Trimper': '百年修剪者',
    'Prison Sprint': '监狱冲刺',
    'Prison Road Trip': '监狱之旅',
    'Frozen': '冻结',
    'Hour Bender': '小时狂欢',
    'Daylusional': '白天的',
    'Chilly': '冰冷',
    'Frosty': '寒霜',
    'Cool': '凉爽',
    'Coldlector': '冷冻机',
    'Expert': '能手',
    'Sitter': '坐着',
    'Gelid': '文件',
    'Amnesia': '健忘症',
    'Savior': '救世主',
    'Connoisseur': '行家',
    'Vacuum': '真空',
    'Aficionado': '业余',
    'Daystroyer': '日托',
    'Seeker': '探求者',
    'Fancier': '爱好者',
    'Adventurer': '冒险家',
    'GigaClearer': '千兆清理者',
    'Coddler': '小贩',
    'Pathfinder': '探路者',
    'Centelium': '中心',
    'Prison Trek': '监狱旅行',
    'Guardian': '守护者',
    'Dayrailed': '日日的',
    'Daylighted': '日光',
    'Cartographer': '制图师',
    'Map Maker': '地图绘制者',
    'Map Annihilator': '地图歼灭者',
    'Map Runner': '地图奔跑者',
    'Curator': '监护人',
    'Caretaker': '看管者',
    'Accumulator': '蓄电池',
    'Nanny': '保姆',
    'Daypocalyptic': '消日剂',
    'When The Wild Things Are': '当疯狂的事',
    'Advocate': '支持者',
    'Glacial': '冰河',
    'Vanquisher': '征服者',
    'Globetrotter': '周游世界',
    'Supervisor': '监督者',
    'Daystiny': '白昼的',
    'Crisp': '易碎',
    'Pioneer': '拓荒者',
    'Prison Tour': '监狱巡视路线',
    'Wall Student': '墙上的学生',
    'Wall Scaler': '墙壁标尺',
    'Prison Hike': '监狱远足',
    'Block Professional': '专业技术人员',
    'Daydicated': '走神的',
    'Prison Hike': '监狱徒步旅行',
    'Acquired Frost': '后天霜冻',
    'Time of Your Life': '你生命中的时光',
    'Brisk': '轻快',
    'A Trimp Through Time': '一个脆皮穿越时空',
    'Quick N Cool': '快速冷却',
    'Frosty Tanker': '结霜油船',
    'Daytermined': '白昼终结',
    'Venti Timeachino': '超大时间',
    'Zone Progress': '区域进度',
    'Trimp Damage': '脆皮伤害',
    'Trimps Owned': '拥有脆皮',
    'Real Estate': '房地产',
    'Total Portals': '总传送门',
    'Total Zone Clears': '总清理区域',
    'Total Map Clears': '地图总清理数',
    'Helium Collection': '氦收集',
    'Helium Per Hour': '氦每小时',
    'Heirloom Collection': '传家宝收藏',
    'Gem Collection': '宝石收集',
    'Daily Bonus': '日常奖励',
    'Humane Run': '人性化战斗',
    'A Time Like No Other': '没有别的时间',
    'Lucky Resolve': '幸运的决心',
    'This is Easy': '这很容易',
    'Blimp Slayer': '飞艇杀手',
    'Groundbreaker': '开拓性',
    'The Beginning': '开端',
    'Determined': '决心',
    'Professor': '教授',
    'Trimp Aficionado': '脆皮业余爱好者',
    'Slayer of Planets': '星际杀手',
    'Motivated': '上进心',
    'Electric': '电气',
    'Stronk': '残端',
    'Endurance': '耐久力',
    'Unwavering': '坚定不移',
    'Coordinated': '配合',
    'Resolved': '已解决',
    'Steadfast': '坚定',
    'Grit': '砂砾',
    'Perseverance': '恒心',
    'Persistence': '坚持',
    'Tenacity': '韧性',
    'The Instigator': '研究者',
    'The Destroyer': '破坏者',
    'The Eradicator': '毁灭者',
    'The Exterminator': '灭火器',
    'Heat Maker': '制热机',
    'Heat Hater': '加热器',
    'Heat Breaker': '热断路器',
    'Heat Slayer': '热火杀手',
    'Heat Expert': '热火专家',
    'Heat Bender': '热弯机',
    'Volcanic': '火山',
    'Magma Master': '岩浆大师',
    'Acre of Nature': '大自然',
    'Aspirer': '灵感',
    'Insane': '癫狂',
    'Spire Master': '尖塔大师',
    'Speed: Spire': '速度: 尖塔',
    'Speed: Spire II': '速度: 尖塔 II',
    'Speed: Spire III': '速度: 尖塔 III',
    'Speed: Spire IV': '速度: 尖塔 IV',
    'Too Many Trimps': '太多脆皮',
    'Overcrowding': '人满为患',
    'This Is Trimp': '这是脆皮',
    'It Takes a Tribe': '建成部落',
    'It Takes a Town': '建成乡镇',
    'It Takes a City': '建成城市',
    'It Takes a Nation': '建成国家',
    'A Milli Trimpi': '百万脆皮',
    'MMMEGATRIMPS': '百万兆脆皮',
    'It Takes a Planet': '建成星球',
    'It Takes a Universe': '建成宇宙',
    'Trimpsponential Growth': '调整增长',
    'Tiny Homes': '小公寓',
    'Residential Development': '住宅开发',
    'Taste for Luxury': '品味奢华',
    'Fancy': '花俏',
    'The Skyline': '地平线',
    'Dimensional Drift': '维漂移',
    'Too Cool For Helium': '对氦来说太酷了',
    'Space From Stars': '星际空间',
    'To Infinity and Beyond': '无穷无尽',
    'Mass Generation': '质量产生',
    'Lead Trimps': '领导脆皮',
    'Silver Trimps': '银色脆皮',
    'Golden Trimps': '金色脆皮',
    'Copper Trimps': '铜色脆皮',
    'Platinum Trimps': '白金脆皮',
    'Iron Trimps': '铁脆皮',
    'Steel Trimps': '钢脆皮',
    'Obsidian Trimps': '黑曜石脆皮',
    'Cobalt Trimps': '钴脆皮',
    'Topaz Trimps': '黄玉脆皮',
    'Diamond Trimps': '钻石脆皮',
    'Transcendental Trimps': '超越脆皮',
    'Finder': '发现者',
    'Angry Runner': '愤怒的赛跑者',
    'Angry Racer': '愤怒的赛车手',
    'Angry Teleporter': '愤怒传送者',
    'Angry Sprinter': '愤怒的运动员',
    'Map Commander': '地图指挥官',
    'Map Slaughterer': '地图屠夫',
    'Dedicated Traveller': '专注的旅行者',
    'Squeaky Dasher': '吱吱嘎嘎的家伙',
    'Gatherer': '采集者',
    'Watchdog': '看门狗',
    'Bushwhacker': '游击队员',
    'Devotee': '信徒',
    'Prison Odyssey': '监狱探险',
    'Blimp Snatcher': '飞艇掠夺者',
    'Wall Contender': '墙壁竞争者',
    'Gusty Gait': '阵风步态',
    'Prison Jog': '监狱慢跑',
    'No Time for That': '不浪费时间',
    'Invisible': '无形',
    'Realtor': '房地产经纪人',
    'Holey': '洞穴',
    'Survivor': '幸存者',
    'Maptastic': '地图符号',
    'Void': '虚空',
    'Helium': '氦',
    'Gym X10': '健身房 X10',
    'Consolation Prize': '安慰奖',
    'Speed: Spire V': '速度:尖塔V',
    'actiVe': '激活',
    'Arctic Accelerator': '北极加速器',
    'driVen': '驱动',
    'Friend of Bots': '机器人的朋友',
    'Nerfed': '削弱',
    'Nerfeder': '继续削弱',
    'Tent City': '帐篷城',
    'Infected': '被感染',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //成就结束
    '': '',
    'Block': '防御',
    'Message Config': '消息设置',
    'Buy Max': '购买最大数量',
    'Save Perk Preset': '保存额外福利预设',
    'Rename Perk Preset': '重命名额外福利预设',
    'Load Perk Preset': '加载额外福利预设',
    'Classy': '经典',
    'Respec': '修改',
    'Health': '生命值',
    'Attack': '攻击力',
    'Set Map At Zone': '在区域内设置地图',
    'Megalumber': '巨型木材',
    'Void Map': '虚空地图',
    'Corruption': '腐败',
    'The Magma': '岩浆',
    'Error': '出错啦',
    'No Snow': '不显示雪',
    'Show Snow': '显示雪',
    //设置项目
    'Default Generator': '默认生成器',
    'Heirloom Animations': '传家宝动画',
    'Alert Mastery': '专精提醒',
    'Allow Big Popups': '允许大弹出窗口',
    'Tiny Perk Buttons': '小额外福利按钮',
    '': '',
    '': '',
    '': '',
    //1.3.地图
    'Dimension of Anger': '愤怒维度',
    'The Prison': '监狱',
    'Bionic Wonderland': '仿生仙境',
    'Bionic Wonderland X': '仿生仙境X',
    'Bionic Wonderland IX': '仿生仙境IX',
    'Bionic Wonderland XI': '仿生仙境XI',
    'The Block': '障碍区',
    'The Wall': '高墙',
    'Trimple Of Doom': '末日之神殿',
    'Imploding Star': '爆炸之星',
    'Tricky Paradise': '整蛊天堂',
    'Haunted Gardens': '闹鬼花园',
    'Whispering Gardens': '耳语花园',
    'Abandoned Gardens': '被遗弃的花园',
    'Bewitched Gardens': '迷人的花园',
    'Terrible Gardens': '可怕的花园',
    'Dark Gardens': '黑暗花园',
    'Blighted Gardens': '枯萎的花园',
    'Sacred Gardens': '神圣花园',
    'Weird Gardens': '怪异的花园',
    'Steamy Gardens': '蒸汽花园',
    'Red Gardens': '红色花园',
    'Calm Gardens': '平静的花园',
    'Evil Gardens': '邪恶花园',
    'Dry Gardens': '干燥的花园',
    'Enchanted Gardens': '魔法花园',
    'Light Gardens': '光明花园',
    'Dirty Gardens': '肮脏的花园',
    'Fiery Gardens': '火热的花园',
    'Deadly Void': '致命的虚空',
    'Heinous Void': '令人发指的虚空',
    'Heinous Pit': '令人发指的坑',
    'Heinous Nightmare': '令人发指的梦魇',
    'Heinous Descent': '令人发指的血统',
    'Poisonous Void': '有毒虚空',
    'Poisonous Pit': '毒坑',
    'Poisonous Nightmare': '有毒的噩梦',
    'Poisonous Descent': '有毒的血统',
    'Deadly Pit': '致命的坑',
    'Deadly Descent': '致命的血统',
    'Deadly Void': '致命的虚空',
    'Deadly Nightmare': '致命的梦魇',
    'Destructive Descent': '破坏性的血统',
    'Destructive Nightmare': '破坏性的噩梦',
    'Destructive Void': '破坏性虚空',
    'Destructive Pit': '破坏性虚坑',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //自动脚本2汉化文本
    'Auto Start Daily': '自动开始日常',
    'Damage to Health Ratio': '健康伤害比率',
    'Finish Challenge2': '完成挑战2',
    'Manual Gather/Build / Auto Gather/Build': '手动收集/建造 / 自动收集/建造',
    'Toggle Automapping2': '切换自动地图2',
    'Auto Allocate Off / Auto Allocate On / Dump into Looting II': '自动分配关闭 / 自动分配开启 / 进入掠夺II',
    'Amalgamator Goal': '合并者目标',

    //未分类20190806
    'Items': '物品',
    'Jobs': '工作',
    'Layout': '布局',
    'Load': '加载',
    'Mine': '矿井',
    'New': '新',
    'Nothing in queue...': '队列中什么都没有......',
    'Other': '其它',
    'Perks': '福利',
    'Portals Used': '使用的传送门',
    'Preset': '预设',
    'Rename': '重命名',
    'Recycle': '回收',
    'Recycle Map': '回收地图',
    'Replace': '替换',
    'Research': '研究',
    'Research first': '研究优先',
    'Resource': '资源',
    'Statistics!': '统计!',
    'Unequip': '卸下',
    'Upgrades': '升级',
    'Upgrade': '升级',
    'Zone': '区域',
    'Achievements': '成就',
    'Abandon Challenge': '放弃挑战',
    'All': '全部',
    'Achieves': '成就',
    'AutoSaving': '自动保存',
    'AutoTraps Off': '自动陷阱 关闭',
    'AutoUpgrade Off': '自动升级 关闭',
    'Back to Search': '返回搜索',
    'Barns Auto-purchased': '谷仓自动购买',
    'Bone Trader': '骨法商人',
    'Build': '建造',
    'Game Saved!': '游戏已保存！',
    'Gather': '收集',
    'Equip': '装备',
    'Export': '导出',
    'Forest': '森林',
    'Import': '导入',
    'Help': '帮助',
    'Nature': '自然',
    'More Info': '更多信息',
    'Chop': '伐木',
    'Continue': '继续',
    'Close': '关闭',
    'Earned All Time': '一直赚的',
    'Equipment': '装备',
    'Exit to Maps': '退出地图',
    'Challenges': '挑战',
    'Challenge': '挑战',
    'Buildings': '建筑',
    'Cancel': '取消',
    'Gathering': '收集中',
    'Chopping': '伐木中',
    'Clear All Perks': '清除所有福利',
    'Random': '随机',
    'Remove': '移除',
    'Repeat Off': '重复 关闭',
    'Repeat Forever': '重复 永远',
    'Quality of Life': '生活质量',
    'Stop Carrying': '停止携带',
    'Stats': '统计',
    'Trimps': '脆皮',
    'Trimps Info': '脆皮信息',
    'Trapping (': '陷阱 (',
    'Tier First': '第1层',
    'Spire': '尖塔',
    'Default Theme': '默认主题',
    'Auto Saving': '自动保存',
    'AutoEquip': '自动装备',
    'AutoFight Off': '自动战斗 关闭',
    'Save': '保存',
    'Settings': '设置',
    'Sea': '海洋',
    'Heirlooms': '传家宝',
    'Heirlooms - Gifts to past you from future you': '传家宝-未来送给过去的你的礼物',
    'Activate Portal': '激活传送门',
    'Alerting': '提醒',
    'Boosts': '提升',
    'Confirming': '确认',
    'Delete Save': '删除存档',
    'Depths': '深渊',
    'Formatting Menu': '格式化菜单',
    'Formatting Perk Levels': '格式化福利等级',
    'General': '常规',
    'Less Breed Timer': '少品种计时器',
    'You have': '你有',
    'Your next mastery costs': '你的下一个专精成本',
    'Void Maps (': '虚空地图 (',
    'AutoPrestige Off': '自动声望 关闭',
    'breeding': '选育',
    'Browse All': '浏览所有',
    'Change Universe': '更改宇宙',
    'Check Traps (': '检查陷阱 (',
    'Choose a Category Below, or Search for a Setting/Keyword': '选择下面的类别，或者搜索设置/关键字',
    'Each Trap allows you to catch 1 thing.': '每个陷阱允许您捕获一样东西。',
    'This is a building in your queue, you\'ll need to click "Build" to build it. Clicking an item in the queue will cancel it for a full refund.': '这是您队列中的一个建筑物，您需要单击“建造”来构建它。 单击队列中的项目将取消它以获得全额退款。',
    'Spawns in Maps': '在地图中产卵',
    'Spawns in World': '在世界中产卵',
    'Spent on Perks': '花在福利上',
    '% bonus': '% 奖励',
    '% extra damage': '% 额外伤害',
    'You are dealing': '你正在交易',
    'View Current Challenge': '查看当前的挑战',
    'Exotic Imp-orts': '异国情调的进展',
    'Download as File': '下载为文件',
    'Copy to Clipboard': '复制到剪贴板',
    'Got it': '知道了',
    'Import your save string! It\'ll be fun, I promise.': '导入存档字符串！ 我保证，这会很有趣。',
    'You do not currently have an active challenge.': '您目前没有进行中的挑战。',
    'You can upgrade any Staff and Shield to HALF the value of your total earned Nu. Nu is not spent, but dictates how powerful your Heirlooms can be!': '您可以将任何棍棒和盾牌升级为HALF，即您获得的总Nu值。 Nu不会花掉，但决定你的传家宝有多强大！',
    'Unlock at Z': '解锁于区域',
    'Trimps Official Discord': '脆皮官方Discord',
    'The currency to upgrade and replace stats,': '用于升级和替换统计数据的货币，',
    'Other Goodies': '其他好东西',
    'One Void Map': '一个虚空地图',
    'Not Saving Online': '不在线保存',
    'Mountain': '山峰',
    'Helium Canisters': '氦罐',
    'Wait to Travel': '等到旅行',
    'Loot off': '掠夺 关闭',
    'Combat off': '战斗 关闭',
    'Unlocks off': '解锁 关闭',
    'Story off': '故事 关闭',
    'Enable Hotkeys': '启用快捷键',
    'Enable Pausing': '启用暂停',
    'Extra Map Info': '额外的地图信息',
    'Confirming Rare Stuff': '确认稀有的东西',
    'Minimal Perk Info': '最小化福利信息',
    'No Timestamps': '没有时间戳',
    'Not Averaging': '不平均',
    'Not Firing For Jobs': '不招聘工作',
    'Not Locking': '不锁定',
    'Nullifium, or Nu,': '虚空物质，或者Nu',
    'Pause the game': '暂停游戏',
    'Pause your game. This will pause all resource gathering, offline progress, and timers. (Hotkey: Space': '暂停你的游戏。 这将暂停所有资源收集，脱机进度和计时器。 （快捷键：空格键',
    'Performance': '性能',
    'Pop-ups and Alerts': '弹出窗口和警报',
    'Popping Heirlooms': '传家宝弹出',
    'Popup Achievements': '成就弹出',
    'Progress Bars': '进度条',
    'Queue Animation': '队列动画',
    'Sheds Auto-purchased': '窝棚自动购买',
    'Showing Tooltips': '显示工具提示',
    'Standard Formatting': '标准格式',
    'Top Right Tips': '右上角提示',
    'Offline Progress': '离线进度',
    'Large Buttons': '大按钮',
    'Large Perk Buttons': '大福利按钮',
    'Outline': '轮廓',
    'You can click a stat to upgrade or replace it.': '您可以单击统计信息以升级或替换它。',
    'You can pause the game by clicking the run timer in the bottom right of the screen. This setting allows you to remove that ability!': '您可以通过单击屏幕右下角的运行计时器来暂停游戏。 此设置允许您删除该功能！',
    'You can also choose to activate a challenge before using your portal. Completing a challenge will earn you a permanent reward. You can abandon or view an active challenge at any time by clicking the "View Perks" button.': '您还可以选择在使用传送门之前激活挑战。 完成挑战将获得永久奖励。 您可以通过单击“查看福利”按钮随时放弃或查看活动挑战。',
    'When the game saves, every 30 minutes also back up a copy online with PlayFab. While using this setting, you will be asked if you want to download your online save if it is ever ahead of the version on your computer. You can also manually import your save from PlayFab through the Import menu.': '当游戏保存时，每30分钟还可以在线备份到PlayFab。 使用此设置时，系统会询问您是否要下载在线保存（如果它比你计算机上的版本新）。 您也可以通过“导入”菜单手动从PlayFab导入保存。',
    'Carry': '携带',
    'Fading': '褪色',
    'Not Fading': '不褪色',
    'No Queue Animation': '没有队列动画',
    'No Progress Bars': '没有进度条',
    'Performance Bars': '性能条',
    'Automatically gain helium equal to the amount you earned on your best run': '自动获得氦，等于您在最佳运行中获得的数量',
    'Locked': '未解锁',
    'Reward': '奖励',
    'can only be gathered by recycling an Heirloom. You can also click on the Heirloom\'s name on this menu to rename it.': '只能通过回收传家宝来收集。 您还可以单击此菜单上的传家宝名称进行重命名。',
    'Any Heirlooms in the "Temporary" section will be recycled for Nullifium on portal.': '“临时”部分中的任何传家宝将在传送门上回收虚空物质。',
    ', better get some more achievements': '，更好地获得更多的成就',
    'You wrecked a Turtlimp!': '你破坏了一只Turtlimp！',
    'Level': '等级',
    'A green shimmer erupts then disappears, and you hit the ground. You look pretty hungry...': '绿色微光爆发后消失，你撞到地面。 你看起来很饿...',
    '1 Trimp just took a dirt nap.': '1只脆皮刚刚小睡了一会儿。',
    'Sweet, thanks.': '甜蜜，谢谢。',
    'Total': '总计',
    'Refresh': '刷新',
    'Base': '基础',
    'Click twice to customize.': '单击两次以自定义。',
    'Fight': '战斗',
    'Item Health': '物品生命',
    'Found a Skeletimp!': '找到了一个Skeletimp！',
    'AutoStructure Off': '自动结构 关闭',
    'AutoJobs Off': '自动工作 关闭',
    'AutoFight': '自动战斗',
    'AutoFight On': '自动战斗 开启',
    'AutoStorage On': '自动存储 开启',
    'AutoUpgrade On': '自动升级 开启',
    'No Modifier': '没有变化',
    'Producing': '生产',
    'Repeat On': '重复 开启',
    'If you abandon this challenge, the portal will become unstable and the world will restart (you\'ll keep permanent bonuses like helium': '如果你放弃这个挑战，传送门将变得不稳定，世界将重新开始（你将获得永久奖励，如氦',
    'Instantly earn the next 12 or 36 hours worth of resources! If you don\'t have enough storage, storage will be purchased (and the cost deducted) automatically.': '立即获得下一个12或36小时的资源！ 如果您没有足够的存储空间，将自动购买存储空间（并扣除成本）。',
    'Hybrid': '混合型',
    'Housing/Tick': '房屋/Tick',
    'Gain Fuel': '获得燃料',
    'Equip First': '装备优先',
    'Dimensional Generator': '维度发生器',
    'Magma Chimp': '岩浆黑猩猩',
    'Weapons First': '武器优先',
    'Forges Auto-purchased': '锻造自动购买',
    'Repeat to': '重复',
    'Runestones per Second': '符石每秒',
    'Sell All': '全部出售',
    'Upgrade (': '升级 (',
    'View Perks': '查看福利',
    'Pause Spire': '暂停尖塔',
    'Fuel': '燃料',
    'Clear Spire III to unlock the Lightning Trap and Knowledge Tower, then raise your Spire\'s Threat to 1100 and build your eleventh Floor.': '清除尖塔 III去解锁闪电陷阱和知识塔，然后将尖塔的威胁提高到1100并建立你的第11层。',
    'Exotic Imp-orts will be unlocked permanently once purchased, and will stick around through portals. Each has a 3% chance to spawn per square and better loot than normal enemies. Collect them all!': '一旦购买，异国情调的ortorts将永久解锁，并将通过传送门保持不变。 每个方块产生3％的几率和比普通敌人更好的战利品。 全部收集它们！',
    'You\'ve got a new Trap and Tower, your Spire is still growing, and your power is growing with it! Your Trimps are slightly annoyed that they have to clean up the occasional Bad Guy that makes it through the Spire and into the town, but they can handle it. They all agree that life in general is just more fun when there\'s a giant Spire grinding Bad Guys at the entrance to their town.': '你有一个新的陷阱和塔，你的尖塔仍在增长，你的力量正在增长！ 你的脆皮有点恼火，他们不得不清理偶尔通过尖塔并进入城镇的坏家伙，但他们可以处理它。 他们都同意，当他们的城镇入口处有一个巨大的尖塔磨坏人们时，生活总体上会更有趣。',
    'While you\'re feeling comfortable maintaining your Spire\'s defenses with the tools you have, you still feel like there\'s something missing. Your Scientists say that they could perhaps create one more Trap and Tower, but again they\'ll need to study a Core from an even higher Spire.': '虽然你觉得使用你拥有的工具来维持尖塔的防御感觉很舒服，但你仍然觉得有些东西缺失了。 你的科学家说，他们或许可以创造一个更多的陷阱和塔，但他们再次需要从更高的尖塔学习核心。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '\n								Get one Heirloom at the chances above, based on highest zone\n							': '根据最高区域获得一个传家宝的机会',
    '\n			Heirlooms are powerful items that can drop with a variety of bonuses and a variety of rarities. You will earn one Heirloom every time a Void Map is completed, and you have a better chance to get higher rarities if you complete the Void Map at higher zones. Once you have an Heirloom, you can click the icon below to select it.': '传家宝是强大的物品，可以随着各种奖金和各种稀有物质下降。 每次完成虚空地图时，您将获得一个传家宝，如果您在更高的区域完成虚空地图，您将有更好的机会获得更高的稀有度。 有了传家宝后，您可以点击下面的图标将其选中。',
    '\n			You can only carry a few Heirlooms (other than the two you have equipped) back through the Portal with you when you use it.': '当你使用它时，你只能随身携带几个传家宝（你装备的两个传家宝除外）。',
    'employed\n					': '就业',
    '\n			Once you\'ve selected an Heirloom, you can see all of its stats on the right side of this screen.': '一旦你选中了传家宝，你可以在这个屏幕的右侧看到它的所有统计数据。',
    '\n			You Found an Heirloom!\n\n			': '你找到一件传家宝！',
    '\n				Current Run\n			': '本轮游戏',
    '\n				Total\n			': '总计',
    '| What\'s New \n					': '新东西',
    'Dark Essence\n										': '黑暗精华',
    '\n													Wind\n											': '风',
    '\n												Ice\n											': '冰',
    '\n												Poison									\n											': '毒',
    '\n											Extra Zones\n										': '额外区域',
    '\n											Perfect Sliders\n										': '完美的滑块',
    '\n											Tokens': '符记',
    '\n											Unlock at Z': '解锁于区域',
    '\n										Biome\n									': '生物群',
    '\n										Difficulty\n									': '困难',
    '\n										Loot\n									': '掠夺',
    '\n										Recycle Map\n									': '回收地图',
    '\n										Run Map\n									': '运行地图',
    '\n										Size\n									': '大小',
    '\n										Special Modifier\n									': '特殊修饰符',
    '\n									AutoFight Off\n								': '自动战斗 关闭',
    '\n									Create\n								': '创建',
    '\n									Exit Spire\n								': '退出尖塔',
    '\n									Fight\n								': '战斗',
    '\n									Finish Daily\n								': '完成日常',
    '\n									Level': '等级',
    '\n									Portal\n								': '传送门',
    '\n									Repeat Off\n								': '重复 关闭',
    '\n									Void Maps\n								': '虚空地图',
    '\n								Buy Bone Portal (100 bones)\n							': '购买骨头传送门 (100 骨头)',
    '\n								Buy Heirloom (30 bones)\n							': '购买传家宝 (30 骨头)',
    '\n								Get one Heirloom at the chances above, based on highest zone\n							': '在上面的机会得到一个传家宝，基于最高区域',
    '\n							Equipped Core': '装备核心',
    '\n							Equipped Shield': '装备盾牌',
    '\n							Equipped Staff': '装备棍棒',
    '\n							One of your storage structures will be more expensive than the amount you can receive from this boost. Spend some resources first to get the most benefit!\n						': '您的一个存储结构将比您从此增强中获得的数量更昂贵。 先花一些资源才能获得最大收益！',
    '\n						Bone Trader\n					': '骨法商人',
    '\n						Close\n					': '关闭',
    '\n						Save': '保存',
    '\n						The Bone Trader trades bones for... bonuses\n					': '骨法商人用骨头交换...奖励',
    '\n						You can earn bones as you progress through the world by killing Skeletimps and Megaskeletimps.\n					': '通过杀死Skeletimps和Megaskeletimps，你可以在世界进步的过程中获得骨骼。',
    '\n						You have': '你有',
    '\n					Carried': '携带的',
    '\n					Temporary': '临时',
    //阻止页面打印

    '': '',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^\n							([\d\.]+) hours\n						$/, '$1 小时'],
    [/^\n							Buy (\d+) Hours \((\d+) bones\)\n						$/, '购买 $1 小时 \($2 骨头\)'],
    [/^Min (.+) Max$/, '最小 $1，最高'],
    [/^While you were away, your Trimps were able to produce (.+) wood.$/, '当你离开时，你的脆皮生产了$1种木材。'],
    [/^(.+) You obliterated a (.+)!$/, '$1 你抹杀了一个 $2!'],
    [/^(.+) You vaporized a (.+)!$/, '$1 你汽化了一个 $2!'],
    [/^(.+) You slew a (.+)!$/, '$1 你杀害了一个 $2!'],
    [/^(.+) You killed a (.+)!$/, '$1 你杀死了一个 $2!'],
    [/^(.+) You destroyed a (.+)!$/, '$1 你摧毁了一个 $2!'],
    [/^(.+) You ruined a (.+)!$/, '$1 你毁灭了一个 $2!'],
    [/^(.+) You extinguished a (.+)!$/, '$1 你灭绝了一个 $2!'],
    [/^(.+) You wrecked a (.+)!$/, '$1 你击毁了一个 $2!'],
    [/^(.+) You liquidated a (.+)!$/, '$1 你清算了一个 $2!'],
    [/^(.+) You demolished a (.+)!$/, '$1 你捣毁了一个 $2!'],
    [/^(.+) You just found (.+) bars of metal! Convenient!$/, '$1 你发现了$2金属棒!方便！'],
    [/^(.+) You just found (.+) wood! That's pretty neat!$/, '$1 你发现了$2木头!这非常棒!'],
    [/^(.+) That guy just left (.+) food on the ground! Sweet!$/, '$1 那家伙刚刚在地上留下了$2的食物！ 甜蜜！'],
    [/^(\d+) workspace$/, '$1 工作空间'],
    [/^(.+)\/sec$/, '$1\/秒'],
    [/^Trade (.+) Bones$/, '交易 $1 骨头'],
    [/^Trade (.+) Bone$/, '交易 $1 骨头'],
    [/^You see (.+) canisters of Helium left on the ground and pick them up. Useful!$/, '你看到$1的氦气罐留在地上并捡起来。 很有用！'],
    [/^(.+) Secs$/, '$1 秒'],
    [/^(.+) Foremen$/, '$1 工头'],
    [/^(.+) Helium$/, '$1 氦'],
    [/^(.+) Tokens$/, '$1 符记'],
    [/^(.+) damage for (.+) seconds in maps$/, '地图中$2秒造成$1的伤害'],
    [/^(.+) Map Loot$/, '$1 地图掠夺'],
    [/^(.+) Breed Speed$/, '$1 选育速度'],
    [/^- (.+) Seconds$/, '- $1 秒'],
    [/^food: ([\d\.]+) \($/, '食物: $1 \('],
    [/^wood: ([\d\.]+) \($/, '木头: $1 \('],
    [/^(.+) workspaces$/, '$1 工作台'],
    [/^(\d+) Mins (\d+) Secs$/, '$1 分钟 $2 秒'],
    [/^\+([\d\.]+)\% Damage$/, '\+$1\% 伤害'],
    [/^Zone (\d+), Cell$/, '区域 $1, 格子'],
    [/^Golden Battle (.+)$/, '金色战斗 $1'],
    [/^Golden Helium (.+)$/, '金色氦 $1'],
    [/^Golden Void (.+)$/, '金色虚空 $1'],
    [/^Bionic Wonderland (.+)$/, '仿生仙境 $1'],
    [/^Knowledge Tower (.+)$/, '知识塔 $1'],
    [/^Lightning Trap (.+)$/, '闪电陷阱 $1'],
    [/^Frost Trap (.+)$/, '冰霜陷阱 $1'],
    [/^Fire Trap (.+)$/, '火焰陷阱 $1'],
    [/^Poison Trap (.+)$/, '毒药陷阱 $1'],
    [/^Condenser Tower (.+)$/, '冷凝器塔 $1'],

]);
