/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],
    //小白牙：
    'Researching': '研究中',
    'Are you sure you want to reset? This will really actually reset your game. You won\'t get anything cool. It will be gone.': '确定要重置吗？这真的会重置你的游戏。你不会因此得到任何酷酷的东西。你的存档会消失的。',
    'This is not the soft-reset you\'re looking for. This will delete your save.': '这不是你要找的软重置。这将删除您的所有存档。',
    'Maybe there\'s something meaty and delicious here to Trap.': '也许在陷阱里有一些肉和美味的东西。',
    'Activate firing mode, turning the job buttons red, and forcing them to fire trimps rather than hire them. The newly unemployed Trimps will start breeding instead of working, but you will not receive a refund on resources.': '激活解雇模式，工作类目下的按钮将变为红色，点击按钮将解雇工种，而不是雇佣他们。新失业的脆皮将开始繁殖而不是工作，你也不会获得任何资源返还。',
    'Apparently the Trimps breed if they\'re not working. Doesn\'t look pleasant.': '很显然，如果脆皮不工作，它们就会繁殖，看起来不大舒服。',
    'Max wood': '最大木头上限',
    'Science Per Second': '每秒获得科技点',
    'Farmers': '农民',
    'Lumberjacks': '伐木工',
    'Item Block': '物品格挡',
    'Breeding': '繁殖',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'You': '你',
    'Food Per Second': '每秒获得食物',
    'Disable firing mode': '关闭解雇模式',
    'Firing': '解雇模式',
    'Figure out how to teach these Trimps to kill some Bad Guys.': '想办法教这些脆皮杀坏人。',
    'DMG': '攻击力',
    'Soldiers': '士兵',
    'Item Attack': '物品攻击',
    'Min': '最小',
    'A nice Shed would allow you to keep more wood on hand.': '一个好的窝棚可以让你保留更多的木材。',
    'The food stores are getting pretty full, maybe you should start thinking about a Barn.': '食物似乎快装不下了，也许你应该开始考虑谷仓。',
    'This book will teach your Trimps to Battle on their own.': '这本书将教你的脆皮自己进行战斗。',
    'Polish the strange Prism you found. When your Trimps bring the polished Prism to Battle': '抛光你发现的奇怪棱镜，你的脆皮将会把抛光棱镜带到战斗中。',
    'This book will increase the block gained from each Gym by 50%.': '这本书使每个健身房增加50%格挡',
    'This book details the fine art of teaching your foremen to actually do stuff instead of just sitting around. When asked, your foremen will start construction on a new Trap if the queue is empty.': '这本书详细介绍了教导你的工头做东西的技术，而不仅仅是坐着。 当被队列为空，你的工头将开始构建新的陷阱。',
    'This book explains methods of using a shield to actually block damage. The current shield will need to be completely destroyed and rebuilt, but it will give block instead of health. <b>This is permanent</b>. $Your Shield Must be Prestige III or higher$': '这本书解释了使用盾牌实际阻止伤害的方法。 当前的盾牌需要被彻底摧毁和重建，但它会给予阻挡而不是生命值。 <b>这是永久的</b>。 $你的盾牌必须是Prestige III或更高$',
    'This book will teach your Farmers, Lumberjacks, Miners, Scientists, and Explorers to all be twice as productive.': '这本书将教你的农民，伐木工人，矿工，科学家和探险家，使其生产力提升为两倍。',
    'Your top scientists are pretty sure this is a Dragimp egg. They know Dragimps love shiny things, maybe it\'ll come out for some gems.': '你的顶尖科学家非常肯定这是一个Dragimp蛋。他们知道拖拽者喜欢闪亮的东西，也许它会为一些宝石而来。',
    'Once again, this Prism will need to be polished before it can offer your Trimps any protection. After it\'s polished, this Prism will grant an additional 50% Prismatic Shield to your Trimps!': '再次，这个棱镜需要经过抛光才能为你的脆皮提供更进一步的保护。 经过抛光后，棱镜将为你的脆皮增加50％的棱镜护盾！',
    'Prismalicious': '优质棱镜',
    'Prismatic': '棱镜护盾',
    'Your scientists are pissed. Not because of anything you did, but this gem seems to be making them mad. It\'ll take some research, but you think you can create a map to the place the gem originated from.': '你的科学家很生气。不是因为你做了什么，而是这颗宝石让他们发疯了。这需要研究一会，但你认为你可以创建一个地图,从而到宝石的起源地。',
    'You just made a map to the Dimension of Anger! Should be fun!': '你刚制造了一张愤怒维度的地图！应该很有趣！',
    'Anger': '愤怒',
    'Unsurprisingly, that Rage Gem you brought back has everyone up the walls. You should probably hurry up and figure out a way to extract the map from inside before your Scientists end up killing eachother.': '不出所料，你带回的那颗愤怒宝石让所有人都兴奋不已。在你们的科学家们互相残杀之前，你们可能应该赶快想办法从内部提取地图。',
    'This book will cause each gym you purchase to increase the block provided by all Gyms by 5%. Each consecutive level of this upgrade will increase the block provided by an additional 1%. <b>The extra block provided compounds per Gym.</b>': '这本书将使你购买的每一个健身房增加所有健身房提供的5%格挡。此升级的每个连续级别将增加1%的格挡。<b>额外的街区为每个健身房提供场地。</b>',
    'This book will teach your Robotrimp how to do a much better job of shrieking, allowing MagnetoShriek to be used on multiple Corrupted cells in addition to Improbabilities. Upgraded MagnetoShriek starts off only being able to affect 1 cell at a time, but each use after purchasing this upgrade will extend the bonus by one additional cell, up to a max of 5 cells (resets on portal). <br/><br/> Each new Bionic Wonderland clear starting at Z185 will permanently increase the cell count cap by 1.': '这本书将教你的机器人如何更好地尖叫，除了不可能的情况外，允许磁尖叫在多个损坏的细胞上使用。升级后的磁尖叫一次只能影响一个电池，但每次购买此升级后使用将增加一个额外的电池，最多5个电池（在门户上重置）。<br/><br/>从z185开始的每一个新的仿生仙境清除将永久增加细胞计数上限1。',
    'The air may be filled with pollution, but your Trimps seem to be getting smarter and a battle technique from what could only be a past life has crept into your memory. This would probably be a good opportunity to teach it to your Trimps. Once researched, you will be able to enter the \'Heap Formation\'. This can be toggled to increase your Trimps\' health by 4x, but reduce block and attack by half.': '空气中可能充满了污染，但你的脆皮似乎变得越来越聪明，一种只可能是过去生活的战斗技巧已经悄悄地进入你的记忆。这可能是一个很好的机会教你的脆皮。一旦研究，你将能够进入"堆形成"。这可以切换到增加你脆皮的生命值4倍，但减少一半的格挡和攻击。',
    'Another formation has crept back into your memory. Where are these coming from? Who are you? Who cares, this one will allow your Trimps to deal 4x damage at the cost of half health and block.': '另一个阵型又悄悄地出现在你的记忆中。这些是从哪里来的？你是谁？谁在乎呢，这个会让你的脆皮造成4倍的伤害，代价是一半的生命和格挡。',
    'Woah, you just remembered that all Trimps lifting their shields in the same direction at the same time can produce a nice protecting wall. Seems like common sense now that you thought of it. This formation increases block by 4x and cuts the amount of block that enemies can pierce by 50%, at the cost of half attack and health.': '哇哦，你刚刚想起来了，所有的装饰物在同一时间向同一个方向举起它们的盾牌都能产生一个很好的防护墙。你想起来像是常识。这个阵型增加4倍的格挡，并减少敌人50%的格挡，同时消耗一半的攻击和生命值。',
    'You really don\'t like reading books, but it seems better than mining yourself.': '你真的不喜欢看书，但它似乎比自己挖掘更好。',
    'You really don\'t believe it, but that book indicates that Trimps can be smart. Better read it and find out how.': '你真的不相信，但那本书表明脆皮可以很聪明。最好读一读，看看怎么做。',
    'This book holds all of the secrets of upper management. Train your Trimps to train other Trimps.': '这本书包含了高层管理的所有秘密。教会你的脆皮训练其他脆皮。',
    'Your scientists think they can study this book to figure out how to train Trimps as Magmamancers. According to your scientists, according to legend, Magmamancers require gems instead of food as sustainance and can increase the rate of Metal gathering more and more as they stay on the same Zone.': '你们的科学家认为他们可以研究这本书，找出如何训练脆皮成为岩浆学家。根据你们的科学家的说法，传说岩浆制造者需要宝石而不是食物作为维持，并且当它们停留在同一区域时，可以越来越多地提高金属聚集的速度。',
    'This book will increase the space gained from each Hut by 100%.': '这本书将使每个小屋的空间增加100%。',
    'This book will increase the space gained from each House by 100%.': '这本书将使每个宅院的空间增加100%。',
    'This book will increase the space gained from each Mansion by 100%.': '这本书将使每个豪宅的空间增加100%。',
    'This book will increase the space gained from each Hotel by 100%.': '这本书将使每个酒店的空间增加100%。',
    'This book will increase the space gained from each Resort by 100%.': '这本书将使每个度假村的空间增加100%。',
    'Researching this will prestige your shield. This will bring your shield to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of stats given. @': '研究这会使你的盾牌重铸。这将使你的盾牌提升1级，并大大增加进一步升级的成本，但也将大大增加给予的格挡。@',
    'Researching this will prestige your dagger. This will bring your dagger to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of attack given. @': '研究这会使你的匕首重铸。这将使你的匕首提升1级，并大大增加进一步升级的成本，但也将大大增加给予的攻击。@',
    'Researching this will prestige your boots. This will bring your boots to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of health given. @': '研究这会使你的靴子重铸。这将使你的靴子提升1级，并大大增加进一步升级的成本，但也将大大增加给予的生命。@',
    'Researching this will prestige your mace. This will bring your mace to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of attack given. @': '研究这会使你的狼牙棒重铸。这将使你的狼牙棒提升1级，并大大增加进一步升级的成本，但也将大大增加给予的攻击。@',
    'Researching this will prestige your helmet. This will bring your helmet to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of health given. @': '研究这会使你的头盔重铸。这将使你的头盔提升1级，并大大增加进一步升级的成本，但也将大大增加给予的生命。@',
    'Researching this will prestige your polearm. This will bring your polearm to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of attack given. @': '研究这会使你的戟重铸。这将使你的戟提升1级，并大大增加进一步升级的成本，但也将大大增加给予的攻击。@',
    'Researching this will prestige your pants. This will bring your pants to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of health given. @': '研究这会使你的裤子重铸。这将使你的裤子提升1级，并大大增加进一步升级的成本，但也将大大增加给予的生命。@',
    'Researching this will prestige your axe. This will bring your axe to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of attack given. @': '研究这会使你的斧头重铸。这将使你的斧头提升1级，并大大增加进一步升级的成本，但也将大大增加给予的攻击。@',
    'Researching this will prestige your shoulderguards. This will bring your shoulderguards to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of health given. @': '研究这会使你的护肩重铸。这将使你的护肩提升1级，并大大增加进一步升级的成本，但也将大大增加给予的生命。@',
    'Researching this will prestige your greatsword. This will bring your greatsword to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of attack given. @': '研究这会使你的巨剑重铸。这将使你的巨剑提升1级，并大大增加进一步升级的成本，但也将大大增加给予的生命。@',
    'Researching this will prestige your breastplate. This will bring your breastplate to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of health given. @': '研究这会使你的胸铠重铸。这将使你的胸铠提升1级，并大大增加进一步升级的成本，但也将大大增加给予的生命。@',
    'Researching this will prestige your arbalest. This will bring your arbalest to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of attack given. @': '研究这会使你的强弩重铸。这将使你的强弩提升1级，并大大增加进一步升级的成本，但也将大大增加给予的攻击。@',
    'Researching this will prestige your gambeson. This will bring your gambeson to level 1 and vastly increase the cost of further upgrades, but will vastly increase the amount of health given. @': '研究这会使你的棉甲重铸。这将使你的棉甲提升1级，并大大增加进一步升级的成本，但也将大大增加给予的生命。@',
    'This book will teach your trimps how to be 10% more efficient at making baby Trimps!': '这本书将教你的脆皮繁殖脆皮宝宝时，提高10%的效率。',
    'This book will teach your Trainers to increase block by an additional 5%!': '这本书将教你的培训师增加5%的格挡。',
    'This book will teach you how to be twice as productive in everything you do! Hurray!': '本书将教你如何在你做的每件事上都有两倍的效率！ 欢呼！',
    'Note that this applies only to your productivity, not workers.': '请注意，这仅适用于您的工作效率，而非工人。',
    'This book will teach your Trimps how to mine 25% faster!': '这本书将教你的脆皮如何增加25%的采矿速度',
    'This book will teach your Trimps how to cut wood 25% faster!': '这本书将教你的脆皮如何增加25%的伐木速度',
    'This book will teach your Trimps how to farm 25% faster!': '这本书将教你的脆皮如何增加25%的务农速度',
    'This book will teach your Trimps how to science things 25% faster!': '这本书将教你的脆皮如何增加25%的研究速度',
    'This book will teach your Trimps how to explore 300% more efficiently!': '这本书将教你的脆皮提升300%探险效率',
    'This book will teach your Trimps how to mine ?% faster!': '',
    'This book will teach your Trimps how to chop wood ?% faster!': '',
    'This book will teach your Trimps how to farm ?% faster!': '',
    'This book will teach your Trimps how to science things ?% faster!': '',
    'It\'s time to get some Trimps up in here.': '是时候在这里获取一些脆皮了。',
    'Ah wood, the building material of kings. The building material of everyone else too, but still.': '啊，木头，国王的建筑材料。其他人的建筑材料，但仍然。',
    'Wet wood won\'t work! Better get a Shed going.': '湿木不起作用！ 最好得到一个窝棚。',
    'You caught your very first Trimp in this new dimension! It can smell other Trimps on you and looks confused. You promptly send him off to work!': '你在这个新的维度中抓住了你的第一个脆皮！ 它可以闻到你的其他脆皮，看起来很困惑。 你及时送他去上班！',
    'Where would you be in life without Science? Not this dimension, that\'s for sure.': '没有科学，你会在哪里生活？ 不是这个维度，这是肯定的。',
    'You\'ll need some wood to build stuff...': '你需要一些木头来造东西。',
    'There\'s a weird impish little creature in the trap. A Trimp, you decide to call it. Since you\'re so creative, you could probably train this Trimp to help out.': '陷阱里有一个奇怪的生物，似乎是一个脆皮，你决定召唤它。既然你这么有创造力，你也许可以训练这个脆皮来帮助你做些什么。',
    'Building': '建造中',
    'Mining': '挖矿中',
    'BLK': '格挡',
    'This planet feels so familiar, yet so foreign. Maybe it\'s time to start sciencing things.': '这颗行星感觉如此熟悉，却又如此陌生。也许是时候开始研究东西了。',
    'War... what is it good for? Exploration, or something.': '战争...有什么好处？探索，或者其它什么。',
    'As you finally step out into the Battle Zones, the first thing you notice is that your Heirlooms feel weaker here. Oh well, 1000 more times into the fray... "': '当你最终走出战区时，你首先注意到的是你的传家宝在这里感觉较弱。 哦，好多了1000次进入战斗......“',
    'The newly established Trimp zoning committee is too busy drooling to approve anything, so you take it on yourself to start building some Huts.': '新成立的脆皮分区委员会忙于流口水，以批准任何事情，所以你自己开始建造一些小屋。',
    'Doesn\'t seem like all of these little guys will fit in your ship. Luckily, you remember how to make small huts for shelter.': '似乎这些小家伙不适合你的船。幸运的是，你还记得如何建造小木屋作为避难所。',
    'The TZC has finally approved a House blueprint. To your surprise, it looks fairly decent! You decide to immediately build some.': 'TZC最终批准了众议院的蓝图。 令你惊讶的是，它看起来相当不错！ 你决定立即建立一些。',
    'Your Trimps look really bored.': '你的脆皮看起来真的很无聊',
    'Better hurry up to the fighting Zones so you don\'t have to sit around here all day watching Trimps breed.': '最好快点到战斗区，这样你就不必整天坐在这里看着脆皮繁殖。',
    'Prestige your Warpstation, increasing the amount of Trimps it can house by 20% and the base cost by 75%. There\'s no turning back, learning these blueprints will make your previous model of Warpstation obsolete but functional, and you will keep all Trimps housed there. Learning this will build one new Warpstation. ': '重铸你的传送站，它可以容纳20％的Trimps，基本成本增加75％。 没有回头路，学习这些蓝图将使你以前的传送站模型过时但功能齐全，并且你将把所有脆皮都留在那里。 学习这将构建一个新的传送站。',
    'Holding Ctrl will cause as many Warpstations as you currently own to be purchased immediately after Gigastation, if you can afford them.': '如果您能负担得起，按住Ctrl将导致在千兆站之后立即购买与您当前拥有的一样多的传送站。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //未分类：
    'primary': '主要',
    'secondary': '次要',
    'exotic': '外来',
    'helium': '氦',
    'essence': '真髓',
    'token': '符记',
    'magma': '岩浆',
    'events': '事件',
    'repeated': '重复',
    'unique': '独特',
    'trimp': '脆皮',
    'enemy': '敌人',
    'food': '食物',
    'Food': '食物',
    'wood': '木头',
    'Wood': '木头',
    'metal': '金属',
    'Metal': '金属',
    'fragments': '碎片',
    'Fragments': '碎片',
    'gems': '宝石',
    'Gems': '宝石',
    'science': '科学',
    'Science': '科学',
    'Fire': '火焰',
    'Frost': '冰霜',
    'Wind': '风',
    'Ice': '冰',
    //传家宝
    'Magmatic Shield': '岩浆盾',
    'Magmatic Staff': '岩浆员工',
    'Legendary Staff': '传奇的员工',
    'Magnificent Shield': '华丽的盾牌',
    'Legendary Shield': '传奇的盾牌',
    'Magnificent Staff': '华丽的员工',
    'Plagued Shield': '天灾之盾',
    'Plagued Staff': '天灾之棍',
    'Epic Shield': '史诗之盾',
    'Epic Staff': '史诗之棍',
    'miner': '矿工',
    'lumber': '木料',
    'farming': '农业',
    'Poison': '毒',
    'Knowledge': '知识',
    'Condenser': '冷凝',
    'Strength': '力量',
    'Lightning': '闪电',
    'Monday': '周一',
    'Tuesday': '周二',
    'Wednesday': '周三',
    'Thursday': '周四',
    'Friday': '周五',
    'Saturday': '周六',
    'Sunday': '周日',
    'Improbability': '无序',
    'Corrupt': '腐败',
    'Penguimp': '企鹅',
    'Magma': '岩浆',
    'Healthy': '健康的',
    'Obliterated': '湮没',
    'Common Core': '共同核心',
    'Rare Core': '稀有核心',
    'Uncommon Core': '罕见核心',
    'Nullifium': '虚空物质',
    'Nu': '虚空物质',
    '': '',
    //传家宝效果
    'Condenser Effect': '冷凝器效果',
    'Runestone Drop Rate': '符石掉率',
    'Fire Trap Damage': '火焰陷阱的伤害',
    'Poison Trap Damage': '毒陷阱的伤害',
    'Lightning Trap Damage': '光陷阱的伤害',
    'Fluffy Exp': '蓬松经验',
    'Plaguebringer': '瘟疫传播',
    'Strength Tower Effect': '力量塔效果',
    'Ss': '尖塔石头',
    '': '',
    '': '',
    '': '',
    '': '',
    //特权
    'Agility': '敏捷',
    'Bait': '诱饵',
    'Pheromones': '信息素',
    'Packrat': '包装',
    'Motivation': '动机',
    'Power': '力量',
    'Toughness': '坚韧',
    'Looting': '掠夺',
    'Trumps': '法宝',
    'Domination': '统治',
    //从这里开始是时间传送门下的按钮
    'Discipline': '纪律',
    'Daily': '日常',
    'Metal': '金属',
    'Size': '尺寸',
    'Balance': '平衡',
    'Scientist V': '科学家 V',
    'Scientist': '科学家',
    'Looting II': '劫掠 II',
    'Carpentry II': '木工 II',
    'Power II': '力量 II',
    'Toughness II': '坚韧 II',
    'Capable': '能力',
    'Cunning': '狡猾',
    'Curious': '好奇',
    'Overkill': '超杀',
    'Resourceful': '足智多谋',
    'Coordinated': '协调',
    'Siphonology': '虹吸学',
    'Anticipation': '预期',
    'Resilience': '弹性',
    'Meditation': '冥想',
    'Relentlessness': '无情',
    'Carpentry': '木工',
    'Artisanistry': '艺术性',
    'Range': '范围',
    'Motivation II': '动机 II',
    'Meditate': '冥想',
    'Decay': '衰变',
    'Trimp': '脆皮',
    'Trapper': '捕手',
    'Electricity': '电流',
    'Frugal': '节俭',
    'Life': '生命',
    'Nom': '美味',
    'Lead': '领导',
    'Watch': '观望',
    'Mapocalypse': '地图的启示',
    'Mapology': '地图学',
    'Coordinate': '协同',
    'Crushed': '粉碎',
    'Toxicity': '毒性',
    'Devastation': '破坏',
    'Corrupted': '腐化',
    'Slow': '迟钝',
    //统计
    'Dead Trimps': '死去的脆皮',
    'Battles Won': '战斗胜利',
    'Battles Lost': '战斗失败',
    'Maps Cleared': '地图清除',
    'Zones Cleared': '区域清除',
    'Gems Collected': '宝石收集',
    'Wormholed Helium': '虫洞氦气',
    'He/Hour this Run': '本次游戏氦/小时',
    'Best He/Hr this Run': '本轮游戏中最高的氦/小时',
    'Highest Void Map Clear': '最高虚空地图清除',
    'Golden Upgrades': '黄金升级',
    'Heirlooms Found': '传家宝发现',
    'Daily Challenge Helium': '每日的挑战氦',
    'World Cells Overkilled': '超杀世界单元格敌人数量',
    'Trimps from Generator': '维度发生器生产的脆皮',
    'Nurseries Closed by Magma': '由岩浆封闭的幼儿园',
    'Zones Liquified': '区域液化',
    'Highest Zone': '最高区域',
    'Total Portals Used': '使用的总传送门',
    'Total Helium Earned': '获得总氦气',
    'Best He/Hour all Runs': '所有轮游戏中最高的氦/小时',
    'Planets Broken': '行星破碎',
    'Burned Nurseries': '燃烧的托儿所',
    'Trap/Tower Kills': '陷阱/塔杀死',
    'Gems Collected': '收集宝石',
    'Maps Cleared': '已清理地图',
    'Zones Cleared': '已清理区域',
    'Trimps Fired': '解雇的脆皮',
    'Food/Wood/Metal': '食物/木头/金属',
    'Total Void Maps Cleared': '总计清理虚空地图',
    'Tokens This Run': '本次游戏获得的符记',
    'Amalgamators Befriended': '合并者帮助',
    'Fluffy Exp This Run': '本次游戏蓬松经验',
    'Fluffy Exp/Hr this Run': '本次游戏蓬松经验/小时',
    'Most Tokens': '符记最高数量',
    'Best Fluffy Exp': '最高蓬松经验',
    'Best Fluffy Exp/Hr': '最高蓬松经验/小时',
    'Best Fluffy Exp/Hr this Run': '本次游戏最高蓬松经验/小时',
    'cache': '缓存',
    'bone': '骨头',
    'Classy': '经典',
    //汉化维度发生器升级标题
    'Efficiency': '效率',
    'Capacity': '容量',
    'Supply': '供给',
    'Overclocker': '超频',
    'Hybridization': '混合',
    'Storage': '存储',
    'Shielding': '屏障',
    'Slowburn': '缓慢燃烧',
    'Supervision': '管理',
    'Simulacrum': '复制',
    'Trap': '陷阱',
    'Barn': '谷仓',
    'Shed': '窝棚',
    'Forge': '锻造室',
    'Hut': '小屋',
    'House': '宅院',
    'Mansion': '豪宅',
    'Hotel': '酒店',
    'Resort': '度假村',
    'Gateway': '出入口',
    'Wormhole': '虫洞',
    'Collector': '集电极',
    'Warpstation': '传送站',
    'Gym': '健身房',
    'Tribute': '贡品',
    'Tribute X': '贡品 X',
    'Nursery': '托儿所',
    'Loot': '战利品',
    'Unlocks': '解锁',
    'Combat': '战斗',
    'enabled': '启用',
    //修饰符
    'Fast Attacks': '快速攻击',
    'Large Cache': '大缓存',
    'Huge Cache': '巨大缓存',
    'Small Savory Cache': '小美味缓存',
    'Small Wooden Cache': '小木制缓存',
    'Small Metal Cache': '小金属缓存',
    'Large Savory Cache': '大美味缓存',
    'Large Wooden Cache': '大木制缓存',
    'Large Metal Cache': '大属缓存',
    'Prestigious': '声望',
    'Legendary': '传奇',
    'Magnificent': '史诗',
    'Magmatic': '岩浆',
    'Ethereal': '暗金',
    'Story': '故事',
    '': '',
    '': '',
    '': '',
    //1.2.标题
    'Shield': '盾牌',
    'Shield X': '盾牌 X',
    'Dagger': '匕首',
    'Dagger X': '匕首 X',
    'Boots': '靴子',
    'Boots X': '靴子 X',
    'Mace': '狼牙棒',
    'Mace X': '狼牙棒 X',
    'Helmet': '头盔',
    'Helmet X': '头盔 X',
    'Polearm': '长矛',
    'Polearm X': '长矛 X',
    'Pants': '裤子',
    'Pants X': '裤子 X',
    'Battleaxe': '战斧',
    'Battleaxe X': '战斧 X',
    'Shoulderguards': '护肩',
    'Shoulderguards X': '护肩 X',
    'Greatsword': '巨剑',
    'Greatsword X': '巨剑 X',
    'Breastplate': '胸铠',
    'Breastplate X': '胸铠 X',
    'Arbalest': '强弩',
    'Arbalest X': '强弩 X',
    'Gambeson': '棉甲',
    'Gambeson X': '棉甲 X',
    'Trap': '陷阱',
    'Trap X': '陷阱 X',
    'Barn': '谷仓',
    'Barn X': '谷仓 X',
    'Shed': '窝棚',
    'Shed X': '窝棚 X',
    'Forge': '锻造室',
    'Forge X': '锻造室 X',
    'Hut': '小屋',
    'Hut X': '小屋 X',
    'House': '宅院',
    'House X': '宅院 X',
    'Mansion': '豪宅',
    'Mansion X': '豪宅 X',
    'Hotel': '酒店',
    'Hotel X': '酒店 X',
    'Resort': '度假村',
    'Resort X': '度假村 X',
    'Gateway': '出入口',
    'Wormhole': '虫洞',
    'Collector': '集电极',
    'Warpstation': '经纱站',
    'Gym': '健身房',
    'Gym X': '健身房 X',
    'Tribute': '贡品',
    'Nursery': '托儿所',
    'Nursery X': '托儿所 X',
    'Farmer': '农民',
    'Farmer X': '农民 X',
    'Lumberjack': '伐木工',
    'Lumberjack X': '伐木工 X',
    'Miner': '矿工',
    'Miner X': '矿工 X',
    'Scientist': '科学家',
    'Scientist X': '科学家 X',
    'Scientists': '科学家',
    'Trainer': '培训师',
    'Trainer X': '培训师 X',
    'Trainers': '培训师',
    'Explorer': '探险家',
    'Explorer X': '探险家 X',
    'Magmamancer': '巫师',
    'Magmamancer X': '巫师 X',
    'Amalgamator': '合并者',
    'Amalgamator X': '合并者 X',
    'Fire Trimps': '解雇脆皮',
    'Gigastation': '千兆站',
    'Geneticistassist': '遗传学家助手',
    'Geneticist': '遗传学家',
    'Agility': '敏捷',
    'Bait': '诱饵',
    'Pheromones': '信息素',
    'Packrat': '包装',
    'Motivation': '动机',
    'Power': '力量',
    'Toughness': '坚韧',
    'Looting': '掠夺',
    'Trumps': '法宝',
    'Custom': '自定义',
    'Confirm Purchase': '确认购买',
    'Looting II': '劫掠 II',
    'Carpentry II': '木工 II',
    'Power II': '力量 II',
    'Toughness II': '坚韧 II',
    'Capable': '能力',
    'Cunning': '狡猾',
    'Curious': '好奇',
    'Overkill': '超杀',
    'Resourceful': '足智多谋',
    'Coordinated': '协调',
    'Coordination': '协作',
    'Siphonology': '虹吸学',
    'Anticipation': '预期',
    'Resilience': '弹性',
    'Meditation': '冥想',
    'Relentlessness': '无情',
    'Battle': '战斗',
    'Carpentry': '木工',
    'Artisanistry': '艺术性',
    'Range': '范围',
    'Motivation II': '动机 II',
    'Bloodlust': '嗜血',
    'Miners': '矿工',
    'Speedminer': '采矿加速',
    'Speedlumber': '砍伐加速',
    'Speedfarming': '耕作加速',
    'Speedscience': '研究加速',
    'Efficiency': '生产效率',
    'Megamace': '巨型狼牙棒',
    'Hellishmet': '地狱头盔',
    'Supershield': '超级盾牌',
    'Dagadder': '攻击匕首',
    'Bootboost': '增速靴',
    'Polierarm': '更长武器',
    'Pantastic': '七分裤',
    'Axeidic': '斧头',
    'Smoldershoulder': '阴燃肩',
    'Greatersword': '更大的剑',
    'Bestplate': '更好的胸铠',
    'Speedexplorer': '探险家加速',
    'Gigastation': '千兆站',
    'TrainTacular': '格挡提升',
    'Potency': '繁殖效率',
    'Max': '最大',
    'AutoStorage': '自动存储',
    'AutoStructure': '自动建筑',
    'Configure AutoStructure': '自动建筑配置',
    'AutoUpgrade': '自动升级',
    'AutoPrestige': '自动重铸装备',
    'AutoGolden': '自动黄金升级',
    'Harmbalest': '伤害平衡',
    'GambesOP': '棉甲OP',
    'Maps': '地图',
    'Rename Preset': '重命名预设',
    'Portal': '传送门',
    'Pierce': '穿刺',
    'Fast': '快速',
    'Save Map Settings': '保存地图设置',
    'Reset Map Settings': '重置地图设置',
    'Recycle All': '回收所有',
    'Map Preset': '回收所有',
    'Gymystic': '健身学',
    'Shieldblock': '盾牌格挡',
    'Trapstorm': '自动陷阱',
    'Blockmaster': '格挡大师',
    'Decay': '衰变',
    'Show/Hide Map Config': '显示/隐藏地图设置',
    'Electricity': '电流',
    'Mastery': '专精',
    'Empowerments of Nature': '自然赋权',
    'Switch Daily': '选择日常挑战',
    'Empower': '赋能',
    'Pressure': '压力',
    'MagnetoShriek': '磁力护盾',
    'Unliving': '亡灵化',
    'Bloodthirst': '嗜血',
    'Scryer Formation': '占卜者阵型',
    'Fire Trap': '火焰陷阱',
    'Frost Trap': '冰霜陷阱',
    'Shift Up': '后移',
    'Shift Down': '前移',
    'Sell Trap/Tower': '出售陷阱/塔',
    'Queue': '队列',
    'Biome': '生物群落',
    'Size': '尺寸',
    'Loot': '掠夺',
    'Special Modifier': '特殊修饰符',
    'Extra Zones': '额外区域',
    'Difficulty': '难度',
    'Perfect Sliders': '完美的滑块',
    'Enchanted Gardens': '魔法花园',
    'Repeat Map': '重复地图',
    'Heirloom': '传家宝',
    'Trustworthy Trimps': '守信的脆皮',
    'World Info': '世界信息',
    'AutoGold': '自动黄金',
    'Threat': '威胁',
    'Enemies': '敌人',
    'Runestones': '符石',
    'Spirestones': '尖塔石头',
    'Trimps Per Second': '每秒脆皮',
    'Max Trimps': '脆皮上限',
    'Scryhard I': '努力占卜 I',
    'Scryhard II': '努力占卜 II',
    'AutoJobs': '自动工作',
    'Legs for Days': '天残脚',
    'Explorer Aura I': '探险家光环 I',
    'Explorer Aura II': '探险家光环 II',
    'Respec Masteries': '洗点',
    'Configure Maps': '配置地图',
    'Map at Spires': '尖塔地图',
    'Import Perk Preset': '导入Perk预设',
    'Export Perk Setup': '导出Perk设置',
    //专精
    'Bionic Magnet I': '仿生磁 I',
    'Bionic Magnet II': '仿生磁 II',
    'Portal Generator': '传送门生成器',
    'Bounty Hunter': '赏金猎人',
    'Home Detector': '家庭探测器',
    'Turkimp Tamer I': '驯兽师 I',
    'Turkimp Tamer II': '驯兽师 II',
    'Turkimp Tamer III': '驯兽师 III',
    'Turkimp Tamer IV': '驯兽师 IV',
    'Void Power I': '虚空力量 I',
    'Void Power II': '虚空力量 II',
    'Void Power III': '虚空力量 III',
    'Metallic Coat': '金属外套',
    'Headstart I': '领先地位 I',
    'Headstart II': '领先地位 II',
    'Headstart III': '领先地位 III',
    'Foremany': '脱颖而出',
    'Map Reducer I': '地图还原剂 I',
    'Map Reducer II': '地图还原剂 II',
    'Double Build': '双重建造',
    'King of Bones I': '骨头之王 I',
    'King of Bones II': '骨头之王 II',
    'Hyperspeed I': '超高速 I',
    'Hyperspeed II': '超高速 II',
    'Blacksmithery I': '黑煅炼 I',
    'Blacksmithery II': '黑煅炼 II',
    'Blacksmithery III': '黑煅炼 III',
    'Quick Gen': '快速第二代',
    'AutoStructure': '自动结构',
    'Magma Flow': '岩浆流',
    'Natural Diplomacy I': '自然外交 I',
    'Natural Diplomacy II': '自然外交 II',
    'Natural Diplomacy III': '自然外交 III',
    'Liquification I': '液化 I',
    'Liquification II': '液化 II',
    'Magmamancermancy': '大巫师',
    'Patience': '忍耐',
    'Still Rowing I': '持续赛艇 I',
    'Still Rowing II': '持续赛艇 II',
    'Strength in Health': '生命的力量',
    'Void Specialization I': '虚空专精 I',
    'Void Specialization II': '虚空专精 II',
    'Megascience': '超级科学',
    'Magmamancers': '岩浆魔法师',
    'Megafarming': '大型农业',
    'Condenser Tower': '冷凝塔',
    'Condenser Tower II': '冷凝塔 II',
    'Knowledge Tower': '知识塔',
    'Knowledge Tower II': '知识塔 II',
    'Poison Trap': '毒物陷阱',
    'Poison Trap II': '毒物陷阱 II',
    'Megaminer': '超级矿工',
    'Lightning Trap': '闪电陷阱',
    'Lightning Trap II': '闪电陷阱 II',
    'Frost Trap IV': '冰霜陷阱 IV',
    'Strength Tower': '力量之塔',
    'Strength Tower II': '力量之塔 II',
    'Strength Tower III': '力量之塔 III',
    'Fire Trap III': '火焰陷阱 III',
    'Trap Layout 1': '陷阱布局 1',
    'Trap Layout 2': '陷阱布局 2',
    'Configure AutoJobs': '配置自动工作',
    'Configure Generator State': '配置生成器状态',
    'Spire Settings': '尖塔设置',
    'Well Fed': '吃的很饱',
    'Fluffy': '蓬松',
    'UberHotel': '超级酒店',
    'UberMansion': '超级豪宅',
    'UberResort': '超级度假村',
    'No Map At Zone': '区域没有地图',
    'UberHouse': '超级宅院',
    'UberHut': '超级小屋',
    'Map Corruption': '地图腐化',
    'Food/Wood/Metal Loot Breakdown': '食物/木头/金属 洗劫一空',
    'Breezy': '活泼的',
    'Deca Build': '十进制构建',
    'Amalgagreater': '融合器',
    'Flufffocus': '蓬松焦点',
    'Excessive': '过度',
    'Flufffinity': '蓬松有限性',
    'Charged Crits': '带电暴击',
    'Confirm Respec Masteries': '确认专精洗点',
    //成就
    'Maptain': '地图符号',
    "What's This For?": '这个是干什么的?',
    'Collector of Shinies': '闪亮的收藏家',
    'Dragimp Lover': 'Dragimp爱人',
    'Expert of Shinies': '闪亮的专家',
    'Jeweller': '珠宝商',
    'Gemaster': '宝石大师',
    'Feats': '专长',
    'Speed: The Block': '速度: 障碍区',
    'Speed: The Wall': '速度: 高墙',
    'Speed: Anger': '速度: 愤怒维度',
    'Speed: Doom': '速度: 末日神殿',
    'Speed: The Prison': '速度: 监狱',
    'Speed: Bionic': '速度: 仿生仙境',
    'Speed: Star': '速度: 爆炸之星',
    'Frigid': '寒冷',
    'Gallop to Doom': '奔向末日',
    'Canter to Doom': '注定失败',
    'Walk to Doom': '走到末日',
    'Trot to Doom': '快步走向末日',
    'Map Destroyer': '地图毁灭者',
    'Centennial Trimper': '百年修剪者',
    'Prison Sprint': '监狱冲刺',
    'Prison Road Trip': '监狱之旅',
    'Frozen': '冻结',
    'Hour Bender': '小时狂欢',
    'Daylusional': '白天的',
    'Chilly': '冰冷',
    'Frosty': '寒霜',
    'Cool': '凉爽',
    'Coldlector': '冷冻机',
    'Expert': '能手',
    'Sitter': '坐着',
    'Gelid': '文件',
    'Amnesia': '健忘症',
    'Savior': '救世主',
    'Connoisseur': '行家',
    'Vacuum': '真空',
    'Aficionado': '业余',
    'Daystroyer': '日托',
    'Seeker': '探求者',
    'Fancier': '爱好者',
    'Adventurer': '冒险家',
    'GigaClearer': '千兆清理者',
    'Coddler': '小贩',
    'Pathfinder': '探路者',
    'Centelium': '中心',
    'Prison Trek': '监狱旅行',
    'Guardian': '守护者',
    'Dayrailed': '日日的',
    'Daylighted': '日光',
    'Cartographer': '制图师',
    'Map Maker': '地图绘制者',
    'Map Annihilator': '地图歼灭者',
    'Map Runner': '地图奔跑者',
    'Curator': '监护人',
    'Caretaker': '看管者',
    'Accumulator': '蓄电池',
    'Nanny': '保姆',
    'Daypocalyptic': '消日剂',
    'When The Wild Things Are': '当疯狂的事',
    'Advocate': '支持者',
    'Glacial': '冰河',
    'Vanquisher': '征服者',
    'Globetrotter': '周游世界',
    'Supervisor': '监督者',
    'Daystiny': '白昼的',
    'Crisp': '易碎',
    'Pioneer': '拓荒者',
    'Prison Tour': '监狱巡视路线',
    'Wall Student': '墙上的学生',
    'Wall Scaler': '墙壁标尺',
    'Prison Hike': '监狱远足',
    'Block Professional': '专业技术人员',
    'Daydicated': '走神的',
    'Prison Hike': '监狱徒步旅行',
    'Acquired Frost': '后天霜冻',
    'Time of Your Life': '你生命中的时光',
    'Brisk': '轻快',
    'A Trimp Through Time': '一个脆皮穿越时空',
    'Quick N Cool': '快速冷却',
    'Frosty Tanker': '结霜油船',
    'Daytermined': '白昼终结',
    'Venti Timeachino': '超大时间',
    'Zone Progress': '区域进度',
    'Trimp Damage': '脆皮伤害',
    'Trimps Owned': '拥有脆皮',
    'Real Estate': '房地产',
    'Total Portals': '总传送门',
    'Total Zone Clears': '总清理区域',
    'Total Map Clears': '地图总清理数',
    'Helium Collection': '氦收集',
    'Helium Per Hour': '氦每小时',
    'Heirloom Collection': '传家宝收藏',
    'Gem Collection': '宝石收集',
    'Daily Bonus': '日常奖励',
    'Humane Run': '人性化战斗',
    'A Time Like No Other': '没有别的时间',
    'Lucky Resolve': '幸运的决心',
    'This is Easy': '这很容易',
    'Blimp Slayer': '飞艇杀手',
    'Groundbreaker': '开拓性',
    'The Beginning': '开端',
    'Determined': '决心',
    'Professor': '教授',
    'Trimp Aficionado': '脆皮业余爱好者',
    'Slayer of Planets': '星际杀手',
    'Motivated': '上进心',
    'Electric': '电气',
    'Stronk': '残端',
    'Endurance': '耐久力',
    'Unwavering': '坚定不移',
    'Coordinated': '配合',
    'Resolved': '已解决',
    'Steadfast': '坚定',
    'Grit': '砂砾',
    'Perseverance': '恒心',
    'Persistence': '坚持',
    'Tenacity': '韧性',
    'The Instigator': '研究者',
    'The Destroyer': '破坏者',
    'The Eradicator': '毁灭者',
    'The Exterminator': '灭火器',
    'Heat Maker': '制热机',
    'Heat Hater': '加热器',
    'Heat Breaker': '热断路器',
    'Heat Slayer': '热火杀手',
    'Heat Expert': '热火专家',
    'Heat Bender': '热弯机',
    'Volcanic': '火山',
    'Magma Master': '岩浆大师',
    'Acre of Nature': '大自然',
    'Aspirer': '灵感',
    'Insane': '癫狂',
    'Spire Master': '尖塔大师',
    'Speed: Spire': '速度: 尖塔',
    'Speed: Spire II': '速度: 尖塔 II',
    'Speed: Spire III': '速度: 尖塔 III',
    'Speed: Spire IV': '速度: 尖塔 IV',
    'Too Many Trimps': '太多脆皮',
    'Overcrowding': '人满为患',
    'This Is Trimp': '这是脆皮',
    'It Takes a Tribe': '建成部落',
    'It Takes a Town': '建成乡镇',
    'It Takes a City': '建成城市',
    'It Takes a Nation': '建成国家',
    'A Milli Trimpi': '百万脆皮',
    'MMMEGATRIMPS': '百万兆脆皮',
    'It Takes a Planet': '建成星球',
    'It Takes a Universe': '建成宇宙',
    'Trimpsponential Growth': '调整增长',
    'Tiny Homes': '小公寓',
    'Residential Development': '住宅开发',
    'Taste for Luxury': '品味奢华',
    'Fancy': '花俏',
    'The Skyline': '地平线',
    'Dimensional Drift': '维漂移',
    'Too Cool For Helium': '对氦来说太酷了',
    'Space From Stars': '星际空间',
    'To Infinity and Beyond': '无穷无尽',
    'Mass Generation': '质量产生',
    'Lead Trimps': '领导脆皮',
    'Silver Trimps': '银色脆皮',
    'Golden Trimps': '金色脆皮',
    'Copper Trimps': '铜色脆皮',
    'Platinum Trimps': '白金脆皮',
    'Iron Trimps': '铁脆皮',
    'Steel Trimps': '钢脆皮',
    'Obsidian Trimps': '黑曜石脆皮',
    'Cobalt Trimps': '钴脆皮',
    'Topaz Trimps': '黄玉脆皮',
    'Diamond Trimps': '钻石脆皮',
    'Transcendental Trimps': '超越脆皮',
    'Finder': '发现者',
    'Angry Runner': '愤怒的赛跑者',
    'Angry Racer': '愤怒的赛车手',
    'Angry Teleporter': '愤怒传送者',
    'Angry Sprinter': '愤怒的运动员',
    'Map Commander': '地图指挥官',
    'Map Slaughterer': '地图屠夫',
    'Dedicated Traveller': '专注的旅行者',
    'Squeaky Dasher': '吱吱嘎嘎的家伙',
    'Gatherer': '采集者',
    'Watchdog': '看门狗',
    'Bushwhacker': '游击队员',
    'Devotee': '信徒',
    'Prison Odyssey': '监狱探险',
    'Blimp Snatcher': '飞艇掠夺者',
    'Wall Contender': '墙壁竞争者',
    'Gusty Gait': '阵风步态',
    'Prison Jog': '监狱慢跑',
    'No Time for That': '不浪费时间',
    'Invisible': '无形',
    'Realtor': '房地产经纪人',
    'Holey': '洞穴',
    'Survivor': '幸存者',
    'Maptastic': '地图符号',
    'Void': '虚空',
    'Helium': '氦',
    'Gym X10': '健身房 X10',
    'Consolation Prize': '安慰奖',
    'Speed: Spire V': '速度:尖塔V',
    'actiVe': '激活',
    'Arctic Accelerator': '北极加速器',
    'driVen': '驱动',
    'Friend of Bots': '机器人的朋友',
    'Nerfed': '削弱',
    'Nerfeder': '继续削弱',
    'Tent City': '帐篷城',
    'Infected': '被感染',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //成就结束
    '': '',
    'Block': '格挡',
    'Message Config': '消息设置',
    'Buy Max': '购买最大数量',
    'Save Perk Preset': '保存额外福利预设',
    'Rename Perk Preset': '重命名额外福利预设',
    'Load Perk Preset': '加载额外福利预设',
    'Classy': '经典',
    'Respec': '修改',
    'Health': '生命值',
    'Attack': '攻击力',
    'Set Map At Zone': '在区域内设置地图',
    'Megalumber': '巨型木材',
    'Void Map': '虚空地图',
    'Corruption': '腐败',
    'The Magma': '岩浆',
    'Error': '出错啦',
    'No Snow': '不显示雪',
    'Show Snow': '显示雪',
    //设置项目
    'Default Generator': '默认生成器',
    'Heirloom Animations': '传家宝动画',
    'Alert Mastery': '专精提醒',
    'Allow Big Popups': '允许大弹出窗口',
    'Tiny Perk Buttons': '小额外福利按钮',
    '': '',
    '': '',
    '': '',
    //1.3.地图
    'Dimension of Anger': '愤怒维度',
    'The Prison': '监狱',
    'Bionic Wonderland': '仿生仙境',
    'Bionic Wonderland X': '仿生仙境X',
    'Bionic Wonderland IX': '仿生仙境IX',
    'Bionic Wonderland XI': '仿生仙境XI',
    'The Block': '障碍区',
    'The Wall': '高墙',
    'Trimple Of Doom': '末日之神殿',
    'Imploding Star': '爆炸之星',
    'Tricky Paradise': '整蛊天堂',
    'Haunted Gardens': '闹鬼花园',
    'Whispering Gardens': '耳语花园',
    'Abandoned Gardens': '被遗弃的花园',
    'Bewitched Gardens': '迷人的花园',
    'Terrible Gardens': '可怕的花园',
    'Dark Gardens': '黑暗花园',
    'Blighted Gardens': '枯萎的花园',
    'Sacred Gardens': '神圣花园',
    'Weird Gardens': '怪异的花园',
    'Steamy Gardens': '蒸汽花园',
    'Red Gardens': '红色花园',
    'Calm Gardens': '平静的花园',
    'Evil Gardens': '邪恶花园',
    'Dry Gardens': '干燥的花园',
    'Enchanted Gardens': '魔法花园',
    'Light Gardens': '光明花园',
    'Dirty Gardens': '肮脏的花园',
    'Fiery Gardens': '火热的花园',
    'Deadly Void': '致命的虚空',
    'Heinous Void': '令人发指的虚空',
    'Heinous Pit': '令人发指的坑',
    'Heinous Nightmare': '令人发指的梦魇',
    'Heinous Descent': '令人发指的血统',
    'Poisonous Void': '有毒虚空',
    'Poisonous Pit': '毒坑',
    'Poisonous Nightmare': '有毒的噩梦',
    'Poisonous Descent': '有毒的血统',
    'Deadly Pit': '致命的坑',
    'Deadly Descent': '致命的血统',
    'Deadly Void': '致命的虚空',
    'Deadly Nightmare': '致命的梦魇',
    'Destructive Descent': '破坏性的血统',
    'Destructive Nightmare': '破坏性的噩梦',
    'Destructive Void': '破坏性虚空',
    'Destructive Pit': '破坏性虚坑',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //自动脚本2汉化文本
    'Auto Start Daily': '自动开始日常',
    'Damage to Health Ratio': '健康伤害比率',
    'Finish Challenge2': '完成挑战2',
    'Manual Gather/Build / Auto Gather/Build': '手动收集/建造 / 自动收集/建造',
    'Toggle Automapping2': '切换自动地图2',
    'Auto Allocate Off / Auto Allocate On / Dump into Looting II': '自动分配关闭 / 自动分配开启 / 进入掠夺II',
    'Amalgamator Goal': '合并者目标',

    //自动脚本3汉化文本
    '(if you want).': '(如果你想).',
    'Add Note/Label': '添加注释/标签',
    'A bunch of U2 stuff added, offline progress still being worked on.': '添加了许多U2内容，离线进度仍在进行中。',
    'Added Arch. Fixed bugs. Updated calc.': '添加了拱门。 修正错误。 更新计算。',
    'All Off/On': '全部关闭/开启',
    'Allocate Perks': '分配津贴',
    'Always Level': '始终等级',
    'AM Portal': 'AM 传送门',
    'Amal Boost': '希望提升',
    'Any': '任何',
    'Black Bog': '黑色沼泽',
    'Black Graphs': '黑色图表',
    'Battle Radon': '战斗氡',
    'AutoTrimps': '自动脆皮',
    'AutoRoboTrimp': '自动化脆皮',
    'AutoEggs': '自动蛋',
    'Auto Worker Ratios': '自动工人比率',
    'Auto Stance': '自动姿态',
    'Auto Maps': '自动地图',
    'Auto Maps On': '自动地图 开启',
    'Auto Maps Off': '自动地图 关闭',
    'Thank you for playing AutoTrimps. Accept and Continue.': '感谢您使用自动脆皮脚本。 接受并继续。',
    'Theme change - AutoTrimps styles updating...': '主题更改-自动脆皮样式更新中...',
    'Third String': '第三个字符串',
    'Throttle Supply (or Capacity': '节流供应(或产能',
    'Trap Trimps': '陷阱抓脆皮',
    'Void + Battle': '虚空 + 战斗',
    'Void Battle': '虚空战斗',
    'Void Maps': '虚空地图',
    'voidMaps': '虚空地图',
    'VoidMaps: NEVER': '虚空地图: 从不',
    'Voids Cell': '虚空格子',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //未分类20190806
    'Items': '物品',
    'Jobs': '工作',
    'Layout': '布局',
    'Load': '加载',
    'Mine': '采矿',
    'New': '新',
    'Nothing in queue...': '队列中什么都没有......',
    'Other': '其它',
    'Perks': '福利',
    'Portals Used': '使用的传送门',
    'Preset': '预设',
    'Rename': '重命名',
    'Recycle': '回收',
    'Recycle Map': '回收地图',
    'Replace': '替换',
    'Research': '研究',
    'Research first': '研究优先',
    'Resource': '资源',
    'Statistics!': '统计!',
    'Unequip': '卸下',
    'Upgrades': '升级',
    'Upgrade': '升级',
    'Zone': '区域',
    'Achievements': '成就',
    'Abandon Challenge': '放弃挑战',
    'All': '全部',
    'Achieves': '成就',
    'AutoSaving': '自动保存',
    'AutoTraps Off': '自动陷阱 关闭',
    'AutoUpgrade Off': '自动升级 关闭',
    'Back to Search': '返回搜索',
    'Barns Auto-purchased': '谷仓自动购买',
    'Bone Trader': '骨法商人',
    'Build': '建造',
    'Game Saved!': '游戏已保存！',
    'Gather': '收集',
    'Equip': '装备',
    'Export': '导出',
    'Forest': '森林',
    'Import': '导入',
    'Help': '帮助',
    'Nature': '自然',
    'More Info': '更多信息',
    'Chop': '伐木',
    'Continue': '继续',
    'Close': '关闭',
    'Earned All Time': '一直赚的',
    'Equipment': '装备',
    'Exit to Maps': '退出地图',
    'Challenges': '挑战',
    'Challenge': '挑战',
    'Buildings': '建筑',
    'Cancel': '取消',
    'Gathering': '收集中',
    'Chopping': '伐木中',
    'Clear All Perks': '清除所有福利',
    'Random': '随机',
    'Remove': '移除',
    'Repeat Off': '重复 关闭',
    'Repeat Forever': '重复 永远',
    'Quality of Life': '生活质量',
    'Stop Carrying': '停止携带',
    'Stats': '统计',
    'Trimps': '脆皮',
    'Trimps Info': '脆皮信息',
    'Trapping (': '陷阱 (',
    'Tier First': '第1层',
    'Spire': '尖塔',
    'Default Theme': '默认主题',
    'Auto Saving': '自动保存',
    'AutoEquip': '自动装备',
    'AutoFight Off': '自动战斗 关闭',
    'Save': '保存',
    'Settings': '设置',
    'Sea': '海洋',
    'Heirlooms': '传家宝',
    'Heirlooms - Gifts to past you from future you': '传家宝-未来送给过去的你的礼物',
    'Activate Portal': '激活传送门',
    'Alerting': '提醒',
    'Boosts': '提升',
    'Confirming': '确认',
    'Delete Save': '删除存档',
    'Depths': '深渊',
    'Formatting Menu': '格式化菜单',
    'Formatting Perk Levels': '格式化福利等级',
    'General': '常规',
    'Less Breed Timer': '少品种计时器',
    'You have': '你有',
    'Your next mastery costs': '你的下一个专精成本',
    'Void Maps (': '虚空地图 (',
    'AutoPrestige Off': '自动声望 关闭',
    'breeding': '繁殖',
    'Browse All': '浏览所有',
    'Change Universe': '更改宇宙',
    'Check Traps (': '检查陷阱 (',
    'Choose a Category Below, or Search for a Setting/Keyword': '选择下面的类别，或者搜索设置/关键字',
    'Each Trap allows you to catch 1 thing.': '每个陷阱允许您捕获一样东西。',
    'This is a building in your queue, you\'ll need to click "Build" to build it. Clicking an item in the queue will cancel it for a full refund.': '这是您队列中的一个建筑物，您需要单击“建造”来构建它。 单击队列中的项目将取消它以获得全额退款。',
    'Spawns in Maps': '在地图中产卵',
    'Spawns in World': '在世界中产卵',
    'Spent on Perks': '花在福利上',
    '% bonus': '% 奖励',
    '% extra damage': '% 额外伤害',
    'You are dealing': '你正在交易',
    'View Current Challenge': '查看当前的挑战',
    'Exotic Imp-orts': '外来的进展',
    'Download as File': '下载为文件',
    'Copy to Clipboard': '复制到剪贴板',
    'Got it': '知道了',
    'Import your save string! It\'ll be fun, I promise.': '导入存档字符串！ 我保证，这会很有趣。',
    'You do not currently have an active challenge.': '您目前没有进行中的挑战。',
    'You can upgrade any Staff and Shield to HALF the value of your total earned Nu. Nu is not spent, but dictates how powerful your Heirlooms can be!': '您可以将任何棍棒和盾牌升级为HALF，即您获得的总Nu值。 Nu不会花掉，但决定你的传家宝有多强大！',
    'Unlock at Z': '解锁于区域',
    'Trimps Official Discord': '脆皮官方Discord',
    'The currency to upgrade and replace stats,': '用于升级和替换统计数据的货币，',
    'Other Goodies': '其他好东西',
    'One Void Map': '一个虚空地图',
    'Not Saving Online': '不在线保存',
    'Mountain': '山峰',
    'Helium Canisters': '氦罐',
    'Wait to Travel': '等到旅行',
    'Loot off': '掠夺 关闭',
    'Combat off': '战斗 关闭',
    'Unlocks off': '解锁 关闭',
    'Story off': '故事 关闭',
    'Enable Hotkeys': '启用快捷键',
    'Enable Pausing': '启用暂停',
    'Extra Map Info': '额外的地图信息',
    'Confirming Rare Stuff': '确认稀有的东西',
    'Minimal Perk Info': '最小化福利信息',
    'No Timestamps': '没有时间戳',
    'Not Averaging': '不平均',
    'Not Firing For Jobs': '不招聘工作',
    'Not Locking': '不锁定',
    'Nullifium, or Nu,': '虚空物质，或者Nu',
    'Pause the game': '暂停游戏',
    'Pause your game. This will pause all resource gathering, offline progress, and timers. (Hotkey: Space': '暂停你的游戏。 这将暂停所有资源收集，脱机进度和计时器。 （快捷键：空格键',
    'Performance': '性能',
    'Pop-ups and Alerts': '弹出窗口和警报',
    'Popping Heirlooms': '传家宝弹出',
    'Popup Achievements': '成就弹出',
    'Progress Bars': '进度条',
    'Queue Animation': '队列动画',
    'Sheds Auto-purchased': '窝棚自动购买',
    'Showing Tooltips': '显示工具提示',
    'Standard Formatting': '标准格式',
    'Top Right Tips': '右上角提示',
    'Offline Progress': '离线进度',
    'Large Buttons': '大按钮',
    'Large Perk Buttons': '大福利按钮',
    'Outline': '轮廓',
    'You can click a stat to upgrade or replace it.': '您可以单击统计信息以升级或替换它。',
    'You can pause the game by clicking the run timer in the bottom right of the screen. This setting allows you to remove that ability!': '您可以通过单击屏幕右下角的运行计时器来暂停游戏。 此设置允许您删除该功能！',
    'You can also choose to activate a challenge before using your portal. Completing a challenge will earn you a permanent reward. You can abandon or view an active challenge at any time by clicking the "View Perks" button.': '您还可以选择在使用传送门之前激活挑战。 完成挑战将获得永久奖励。 您可以通过单击“查看福利”按钮随时放弃或查看活动挑战。',
    'When the game saves, every 30 minutes also back up a copy online with PlayFab. While using this setting, you will be asked if you want to download your online save if it is ever ahead of the version on your computer. You can also manually import your save from PlayFab through the Import menu.': '当游戏保存时，每30分钟还可以在线备份到PlayFab。 使用此设置时，系统会询问您是否要下载在线保存（如果它比你计算机上的版本新）。 您也可以通过“导入”菜单手动从PlayFab导入保存。',
    'Carry': '携带',
    'Fading': '褪色',
    'Not Fading': '不褪色',
    'No Queue Animation': '没有队列动画',
    'No Progress Bars': '没有进度条',
    'Performance Bars': '性能条',
    'Automatically gain helium equal to the amount you earned on your best run': '自动获得氦，等于您在最佳运行中获得的数量',
    'Locked': '未解锁',
    'Reward': '奖励',
    'can only be gathered by recycling an Heirloom. You can also click on the Heirloom\'s name on this menu to rename it.': '只能通过回收传家宝来收集。 您还可以单击此菜单上的传家宝名称进行重命名。',
    'Any Heirlooms in the "Temporary" section will be recycled for Nullifium on portal.': '“临时”部分中的任何传家宝将在传送门上回收虚空物质。',
    ', better get some more achievements': '，更好地获得更多的成就',
    'You wrecked a Turtlimp!': '你破坏了一只Turtlimp！',
    'Level': '等级',
    'A green shimmer erupts then disappears, and you hit the ground. You look pretty hungry...': '绿色微光爆发后消失，你撞到地面。 你看起来很饿...',
    'Sweet, thanks.': '甜蜜，谢谢。',
    'Total': '总计',
    'Refresh': '刷新',
    'Base': '基础',
    'Click twice to customize.': '单击两次以自定义。',
    'Fight': '战斗',
    'Item Health': '物品生命',
    'Found a Skeletimp!': '找到了一个Skeletimp！',
    'AutoStructure Off': '自动结构 关闭',
    'AutoJobs Off': '自动工作 关闭',
    'AutoFight': '自动战斗',
    'AutoFight On': '自动战斗 开启',
    'AutoStorage On': '自动存储 开启',
    'AutoUpgrade On': '自动升级 开启',
    'No Modifier': '没有变化',
    'Producing': '生产',
    'Repeat On': '重复 开启',
    'If you abandon this challenge, the portal will become unstable and the world will restart (you\'ll keep permanent bonuses like helium': '如果你放弃这个挑战，传送门将变得不稳定，世界将重新开始（你将获得永久奖励，如氦',
    'Instantly earn the next 12 or 36 hours worth of resources! If you don\'t have enough storage, storage will be purchased (and the cost deducted) automatically.': '立即获得下一个12或36小时的资源！ 如果您没有足够的存储空间，将自动购买存储空间（并扣除成本）。',
    'Hybrid': '混合型',
    'Housing/Tick': '房屋/Tick',
    'Gain Fuel': '获得燃料',
    'Equip First': '装备优先',
    'Dimensional Generator': '维度发生器',
    'Magma Chimp': '岩浆黑猩猩',
    'Weapons First': '武器优先',
    'Forges Auto-purchased': '锻造自动购买',
    'Repeat to': '重复',
    'Runestones per Second': '符石每秒',
    'Sell All': '全部出售',
    'Upgrade (': '升级 (',
    'View Perks': '查看福利',
    'Pause Spire': '暂停尖塔',
    'Fuel': '燃料',
    'Clear Spire III to unlock the Lightning Trap and Knowledge Tower, then raise your Spire\'s Threat to 1100 and build your eleventh Floor.': '清除尖塔 III去解锁闪电陷阱和知识塔，然后将尖塔的威胁提高到1100并建立你的第11层。',
    'Exotic Imp-orts will be unlocked permanently once purchased, and will stick around through portals. Each has a 3% chance to spawn per square and better loot than normal enemies. Collect them all!': '一旦购买，外来的进展将永久解锁，并将通过传送门保持不变。 每个方块产生3％的几率和比普通敌人更好的战利品。 全部收集它们！',
    'You\'ve got a new Trap and Tower, your Spire is still growing, and your power is growing with it! Your Trimps are slightly annoyed that they have to clean up the occasional Bad Guy that makes it through the Spire and into the town, but they can handle it. They all agree that life in general is just more fun when there\'s a giant Spire grinding Bad Guys at the entrance to their town.': '你有一个新的陷阱和塔，你的尖塔仍在增长，你的力量正在增长！ 你的脆皮有点恼火，他们不得不清理偶尔通过尖塔并进入城镇的坏家伙，但他们可以处理它。 他们都同意，当他们的城镇入口处有一个巨大的尖塔磨坏人们时，生活总体上会更有趣。',
    'While you\'re feeling comfortable maintaining your Spire\'s defenses with the tools you have, you still feel like there\'s something missing. Your Scientists say that they could perhaps create one more Trap and Tower, but again they\'ll need to study a Core from an even higher Spire.': '虽然你觉得使用你拥有的工具来维持尖塔的格挡感觉很舒服，但你仍然觉得有些东西缺失了。 你的科学家说，他们或许可以创造一个更多的陷阱和塔，但他们再次需要从更高的尖塔学习核心。',
    'Sell a Trap/Tower': '出售一个陷阱/塔',
    'Shrink Window': '收缩窗口',
    ' Lv': ' 等级',
    'Back to World': '返回世界',
    'can only be gathered by recycling an Heirloom.': '只能通过回收传家宝来收集。',
    'Cell': '格子',
    'Check Traps (': '检查陷阱 (',
    'Chrome and Firefox are currently the only fully supported browsers.': 'Chrome和Firefox当前是唯一受完全支持的浏览器。',
    'Click on an Achievement on this screen to track it!': '单击此屏幕上的成就进行跟踪！',
    'Starting...': '开始...',
    'Stop Here': '停在这里',
    'Wanna run a map?': '想运行地图吗？',
    'What is This?!': '这是什么？！',
    'World Level Map': '世界等级地图',
    'You can also click on the Heirloom\'s name on this menu to rename it, or click on the icon to change it!': '您也可以在此菜单上单击传家宝的名称来重命名，或单击图标进行更改！',
    'Exotic Imp-orts will be unlocked permanently once purchased, and will stick around through portals. Each has a 3% chance to spawn per cell and better loot than normal enemies. Collect them all!': '购买后，外来的进展将会永久解锁，并将通过门户网站持续存在。 每个单位有3％的几率产生一个单位，并且比普通敌人有更好的战利品。 全部收集！',
    'click here to send a message on Reddit': '单击此处在Reddit上发送消息',
    'community-created Trimps Wiki!': '社区创建的脆皮 Wiki！',
    'If you need to contact the developer for any reason,': '如果出于任何原因需要与开发人员联系，',
    'If you want to read about or discuss the finer details of Trimps mechanics, check out the': '如果您想阅读或讨论脆皮力学的更多细节，请查看',
    'Need help, found a bug or just want to talk about Trimps? Check out the': '需要帮助，发现错误或只是想谈论脆皮？ 看看',
    'or come hang out in the new': '或参加新的功能',
    'or find Greensatellite in the Trimps Discord.': '或在脆皮 Discord中找到Greensatellite。',
    'If you would like to make a donation to help support the development of Trimps, you can now do so with PayPal! If you want to contribute but can\'t afford a donation, you can still give back by joining the community and sharing your feedback or helping others. Thank you either way, you\'re awesome!': '如果您想捐款以支持脆皮的开发，现在就可以使用PayPal！ 如果您想捐款但负担不起，您仍然可以通过加入社区，分享您的反馈或帮助他人来回馈社会。 无论哪种方式，谢谢你，你真棒！',
    'Build your first  Hut': '建立你的第一个小屋',
    'Complete Zone': '完成的区域',
    'This is your save string. There are many like it but this one is yours. Save this save somewhere safe so you can save time next time.': '这是您的存档字符串。 有很多类似的东西，但这是你的。 将此保存到安全的地方，以便下次节省时间继续玩。',
    'Has room for 3 more lovely Trimps. All Trimp housing has enough workspaces for only half of the Trimps that can live there.': '有更多的空间容纳3个可爱的脆皮。所有的脆皮住房有足够的工作空间，只有一半的脆皮可以住在那里。',
    'Increases your maximum food by 100%.': '增加你的食物上限100%。',
    'Increases your maximum wood by 100%.': '增加你的木头上限100%。',
    'Switching to this option will spend the majority of your resources with each purchase.': '转换到这个选项将花费你的大部分资源在每次购买。',
    'Send your poor Trimps to certain doom in the battlefield. You\'ll get cool stuff though, they\'ll understand. (Hotkey: F': '将您可怜的脆皮带到战场上的某些厄运。 他们会明白，但是您会得到很棒的东西。 （热键：F',
    'You have been in this Zone ': '你一直在这个区域',
    'Amount': '数量',
    'Line Total': '总行数',
    'You found plans for a shield! It even tells you how to upgrade it, if you have enough wood. That was nice of that Bad Guy.': '您已经找到了盾牌的计划！ 如果您有足够的木材，它甚至会告诉您如何升级。 那个坏家伙真好。',
    'You found an ancient book titled Bloodlust. You should look at it or something.': '您发现一本古老的书，名为《嗜血》。 您应该看一下它。',
    'Allow the Trimps to start fighting on their own whenever their town gets overcrowded (Hotkey: A': '每当镇上人满为患时，让脆皮自己开始战斗（热键：A',
    'You vaporized a Snimp!': '您汽化了一只Snimp！',
    'You found plans for a Dagger! Fancy!': '你找到匕首的设计图了!真想不到!',
    'Your Trimps managed to pull 1 perfectly preserved bone from that Skeletimp!': '您的脆皮设法从那只Skeletimp中取出了1个保存完好的骨头！',
    'You destroyed an Elephimp!': '您摧毁了一只大象！',
    'You extinguished an Elephimp!': '你扑杀了一只大象',
    'You demolished an Elephimp!': '您拆散了一只大象！',
    'You obliterated an Elephimp!': '你消灭了一头大象!',
    'You found plans for Boots! Swell!': '您找到了靴子的计划！ 隆起！',
    'You vaporized a Chimp!': '您蒸发了一只黑猩猩！',
    'You found a book called Speedminer!': '您发现了一本书叫做采矿加速！',
    'You found a book called Speedlumber! It looks long.': '您找到了一本叫做砍伐加速的书！ 看起来很长。',
    'Your Trimps threw a party while you were out': '你不在家时，你的脆皮开了个聚会',
    'Starting Offline Progress... (Updates every 2000 processed loops': '开始同步离线进度……(每处理2000个循环更新一次',
    'Estimated completion in': '估计完成时间',
    'our Trimps were a few minutes away from burning the place down': '我们的脆皮距离烧毁这个地方只有几分钟的路程',
    'Some Trimps toilet papered your ship': '一些脆皮用掉了你船上的卫生纸',
    'Wow, such speed': '哇，这么快',
    'Progress has slowed to a crawl!': '进展慢如蜗牛!',
    'Your Trimps didn\'t do dishes while you were gone': '你不在的时候，你的脆皮们不洗碗',
    'Your Trimps really missed you': '你的脆皮们真的很想你',
    'A Scientist has been locked outside all night': '一位科学家整夜都被锁在外面',
    'combines Time Warp and Trustworthy Trimps into the best offline experience that Science can buy. Time Warp caps at 24 hours, so using Hybrid Offline will grant Trustworthy Trimps at the beginning of your Time Warp for all offline time over 24 hours, and will also grant Trustworthy Trimps for any extra time should you choose to end Time Warp early. Note that the Portal Time and Time in Zone clocks will advance for all time granted by Trustworthy Trimps and by Time Warp.': '把时间扭曲和值得信赖的小事结合成科学能买到的最佳线下体验。时间偏差上限在24小时，所以使用混合离线将授予值得信赖的脆皮在你的时间偏差开始时超过24小时的所有离线时间，也将授予值得信赖的脆皮任何额外的时间，如果你选择结束时间偏差早。请注意，传送门时间和区域时钟中的时间将按照可信脆皮和时间偏差所允许的所有时间提前。',
    'Hybrid Offline': '混合离线',
    'If your Trimps look stuck, you can always': '如果您的脆皮看起来卡住了，您可以随时',
    'Lost Time': '失去的时间',
    'Neat': '利落',
    'No Offline Progress': '没有离线进度',
    'or in Settings -> Other': '或在 设置->其他中',
    'This setting can be changed from the Time Warp screen': '可以从“时间扭曲”屏幕更改此设置',
    'Time Warp Only': '仅时间扭曲',
    'to regain full control of your Trimps, and you\'ll still receieve resources from Trustworthy Trimps for any unused Time Warp time!': '恢复对脆皮的完全控制权，并且在任何未使用的时间扭曲的时间内，您仍然会从T值得信任的脆皮那里获得资源！',
    'Trustworthy Trimps Only': '仅值得信任的脆皮',
    'While you were out, your Trimps didn\'t get much done - unless you count destruction of property. Luckily you have a Time Portal! While you can\'t go forward in time, you can go back to keep the Trimps in line and I\'ll wait here for you': '当您出门在外时，您的脆皮并没有完成太多工作-除非您算出财产损失。 幸运的是您有一个时间门户！ 虽然您无法及时前进，但可以返回以使脆皮保持一致，我将在这里等您',
    'While you\'re in the past, everything will progress like normal, just much faster. The temporal displacement effects give you blurry vision and a headache (making fine control impossible), but you can force your Trimps to stop and run 1 map whenever you want for each 8 hours spent offline! Maps created this way will use your first preset settings at your selected level with Repeat for Items and Exit to World.': '过去，一切都会像往常一样进展，只是速度更快。 暂时的位移效果使您视力模糊和头痛（无法进行精细控制），但是只要您希望每8小时离线花费一次，就可以强制Trimps停止并运行1张地图！ 以这种方式创建的地图将在您选择的级别上使用您的第一个预设设置，并重复项目和退出世界。',
    'will cause no extra resources to be earned and no time to be warped when you return to the game. The Portal and Zone timers will not advance while offline, and the game will be in the same state you left it when you come back. This can be useful for speedrun achievements or if you just really really don\'t trust your Trimps when you\'re gone.': '当您返回游戏时，将不会获得任何额外的资源，也不会浪费任何时间。 离线状态下，传送门和区域计时器不会前进，并且游戏将保持与您返回时相同的状态。 这对于加快速度取得成就或在走后真的不信任Trimps时很有用。',
    'will grant up to 24 hours of your offline progress as Time Warp without granting any extra resources from Trustworthy Trimps at the beginning (for time over 24 hours), or at the end (for canceled Time Warp time). This can also be useful for timed runs or tracking stats, as the time added will be capped to however much time you spend in Time Warp.': '在开始时（超过24小时的时间）或结束时（对于取消的时间扭曲时间），系统最多可以将您的离线进度作为时间扭曲授予24小时，而无需从值得信任的脆皮授予任何额外的资源。这也很有用 定时运行或跟踪统计信息，因为增加的时间将限制为您花费时间扭曲的时间。',
    'will skip Time Warp when you come back and grant resources for all time offline from Trustworthy Trimps. For when you want to get back in the game as soon as possible!': '您回来时将跳过时间扭曲，并从值得信任的脆皮离线分配所有时间的资源。 当您想尽快回到游戏中时！',
    'You can change your Offline Progress setting to suit your needs!': '您可以更改脱机进度设置以适合您的需求！',
    'You can Time Warp for 100% of the time you spent offline, up to a maximum of 24 hours.': '您可以将离线时间的100％时间扭曲，最多24小时。',
    'A building where your Trimps can work out. Each Gym increases the amount of damage each trimp can block by 4.': '一个你可以锻炼脆皮的建筑。每个健身房增加每个脆皮可以阻挡的伤害4。',
    'At least their feet will be safe. Adds 6 health to each soldier per level': '至少他们的脚是安全的。每升一级增加6点生命值',
    'Increases your maximum metal by 100%.': '增加你的金属上限100%。',
    'It\'s kind of heavy for your Trimps, but they\'ll manage. Adds 3 attack to each soldier per level': '这对你的脆皮来说有点重，但他们会处理的。每升一级增加3个攻击',
    'Provides a decent amount of protection to the Trimps\' heads, adding 10 health to each soldier per level.': '为脆皮的头部提供足够的保护，每级增加10点生命值。',
    '- Bone': '- 骨头',
    '- Enemy': '- 敌人',
    '- Events': '- 事件',
    '- Exotic': '- 外来的',
    '- Primary': '- 主要',
    '- Repeated': '- 重复',
    '- Secondary': '- 次要的',
    '- Unique': '- 独特',
    'Here you can finely tune your message settings, to see only what you want from each category. Mouse over the name of a filter for more info.': '在这里，你可以微调你的消息设置，只看到你想从每个类别。鼠标移到过滤器的名称上以获取更多信息。',
    'Repeated': '重复的',
    'Unique': '独特的',
    'Confirm': '确认',
    'Bone': '骨头',
    'Enemy': '敌人',
    'Events': '事件',
    'Exotic': '外来的',
    'Primary': '主要',
    'Secondary': '次要的',
    '- Log all unlocks that only drop once per portal, such as Gyms or Miners.': '- 记录每个传送门仅释放一次的所有解锁，如健身房或矿工。',
    '- Log all unlocks that drop more than once per run, such as Speedfarming or Coordination.': '- 记录每次运行多次下降的所有解锁，例如耕作加速或协作。',
    '- Log all combat messages involving the enemy.': '- 记录所有与敌人有关的战斗信息。',
    '- Log all combat messages involving your Trimps.': '-记录所有涉及脆皮的战斗消息。',
    '- Log Bone drops from Skeletimps.': '- 记录来自骷髅脆皮的骨头掉落',
    '- Log drops and messages from temporary events, such as holidays.': '- 记录掉落和来自临时事件（例如假期）的消息。',
    '- Log Helium rewards.': '- 记录氦奖励。',
    '- Log the common loot items: Food, Wood, and Metal.': '- 记录常见的战利品：食物，木材和金属。',
    '- Log the less common loot items: Gems, Fragments, Territory Bonus, and others.': '-记录不太常见的战利品：宝石，碎片，领土奖金等。',
    '- Log the rewards granted by Exotic Imports.': '-记录值得信任的脆皮授予的奖励。',
    'Each trainer will increase the base amount your soldiers can block by 20%.': '每位训练师都会将您的士兵可以格挡的基础伤害数量提高20％。',
    'This Bad Guy is fast and attacks first': '这个坏家伙速度快并且首先攻击',
    'Reach Z5 after losing no more than one fight per Zone.': '每个区域最多输完一场战斗后达到Z5。',
    '45 seconds of production for 1 random resource': '1个随机资源的生产时间为45秒',
    '5 seconds of production for all basic resources': '所有基本资源的制作时间为5秒',
    '50% Trimp Damage': '50% 脆皮伤害',
    'Automatically gain Helium equal to the amount you earned on your best run.': '自动获得等于您在最佳运行中获得的氦气量。',
    'Buy Chronoimp (50 bones': '购买 Chronoimp（50骨头',
    'Buy Feyimp (50 bones': '购买 Feyimp（50骨头',
    'Buy Flutimp (50 bones': '购买 Flutimp（50骨头',
    'Buy Jestimp (50 bones': '购买 Jestimp（50骨头',
    'Buy Magnimp (50 bones': '购买 岩浆脆皮（50骨头',
    'Buy Tauntimp (50 bones': '购买 Tauntimp（50骨头',
    'Buy Titimp (50 bones': '购买 Titimp（50骨头',
    'Buy Venimp (50 bones': '购买 吸血鬼脆皮（50骨头',
    'Buy Whipimp (50 bones': '购买 Whipimp（50骨头',
    'Buy Goblimp (50 bones': '购买 哥布林脆皮（50骨头',
    'First, select an Imp (50 bones': '首先，选择一个小鬼（50骨头',
    'Drops Fragments': '掉落碎片',
    'Golden Maps (20 bones': '金色地图（20骨头',
    'Grants 0.3% Trimp breed speed': '获得0.3％脆皮繁殖速度',
    'Grants 0.3% Trimp resource production speed': '授予0.3％的脆皮资源生产速度',
    'Grants an extra 0.3% of current 脆皮': '额外捐赠当前脆皮的0.3％',
    'Heliumy (100 bones': '氦（100骨头',
    'Quick Trimps (20 bones': '快速脆皮（20骨头',
    'Sharp Trimps (25 bones': '尖刺脆皮（25骨头',
    'Single Run Bonuses': '一次性奖金',
    'These all last until your next soft reset. Use them wisely!': '这些全部持续到下一次软重置。 明智地使用它们！',
    'This thing is big and pointy. It adds 4 attack to each soldier per level': '这个东西又大又尖。每级增加4个攻击',
    'A better house for your Trimps! Each house supports up to 5 more Trimps.': '给您的脆皮更好的房子！ 每个房屋最多可支持5个脆皮。',
    'Gain 1 map for each 8 hours away': '每8个小时可获得1张地图',
    'No maps available': '没有可用的地图',
    'Pants designed specificially for the little Trimps! Adds 14 health to each soldier per level.': '专为小脆皮设计的裤子！ 每级士兵增加14点生命。',
    'Send your misbehaving Trimps to the mines for some therapeutic work. Each Miner can find and smelt 0.78 bars of metal per second.': '',
    'Wood Per Second': '木头每秒产量',
    'Metal Per Second': '金属每秒产量',
    'You found a book called Speedfarming! It looks delicious!': '您发现了一本书叫做耕作加速！ 看起来很好吃！',
    'Max Food': '食物上限',
    'Max Metal': '金属上限',
    'Max Wood': '木头上限',
    'Apparently your scientists are vegetarians. Hurray, more Turkimp for you!': '显然，您的科学家是素食主义者。 祝您好运！',
    'That Turkimp was delicious, and you have leftovers. If you set yourself to gather Food, Wood, or Metal while this buff is active, you can share with your workers to increase their gather speed by': 'Turkimp真好吃，而且剩饭剩菜了。如果您在这种抛光状态下设置自己收集食物，木材或金属，则可以与您的工人分享以提高他们的收集速度。',
    'You found a book called Speedscience! What do you think it could possibly do?!': '您发现了一本书叫做研究加速！ 您认为它可能会做什么？',
    'You found a book discussing tactics for better blocking!': '您发现了一本书，讨论了更好的封锁策略！',
    'You found plans for Shoulderguards!': '您找到了护肩设计图！',
    'You killed an Elephimp!': '您杀死了一只大象！',
    'You liquidated an Elephimp!': '您清算了一只大象！',
    'You vaporized a Penguimp!': '您蒸发了一只Penguimp！',
    'You wrecked an Elephimp!': '你毁了一只大象！',
    'These shoulderguards will help keep your Trimps\' necks and shoulders safe, and they look cool too. Adds 23 health to each soldier per level': '这些护肩有助于保持脆皮的脖子和肩膀安全，而且看起来也很酷。 每级士兵增加23点生命',
    'This weapon is pretty intimidating, but your Trimps think they can handle it. Adds 7 attack to each soldier per level': '这种武器非常吓人，但您的脆皮认为他们可以应付。 每级士兵增加7点攻击力',
    'A building where your Trimps can work out. Each Gym increases the amount of damage each trimp can block by 6.': '您的脆皮可以锻炼的建筑物。 每个健身房都会使每个修剪可以阻止的伤害增加6点。',
    'This sword looks sweet. Seriously, if you could see it you\'d think it looked sweet. Trust me. Adds 9 attack to each soldier per level': '这把剑看起来很甜美。 认真地说，如果您看到它，您会认为它看起来很甜。 相信我。 每级向每名士兵增加9点攻击',
    'You can only purchase 1 Barn at a time.': '您一次只能购买1个谷仓。',
    'You can only purchase 1 Forge at a time.': '您一次只能购买1个锻造室。',
    'You can only purchase 1 Shed at a time.': '您一次只能购买1个窝棚。',
    'Build your first  House': '建造你的第一所宅院',
    'Build your first  Mansion': '建立你的第一座豪宅',
    'but you wish you had a few more achievements': '但你希望自己能再有一些成就',
    ', you\'d do fine with a few more achievements': '，您会再取得一些成就',
    'Progress: You lost more than once on Z': '进度：您输了不止一次在Z',
    'building,': '建筑,',
    'CRIT!!': '暴击!!',
    'CRIT!': '暴击!',
    'Got it!': '得到它！',
    'Use them wisely...': '明智地使用它们...',
    'What\'s New': '最新消息',
    'You stumble across a large locked chest, unlike anything you\'ve ever seen. The lock looks rusty, you smack it with a rock, and it falls right off. Immediately the ground shakes and cracks beneath your feet, intense heat hits your face, and Magma boils up from the core.': '您偶然发现了一个巨大的上锁的胸部，这与您见过的任何东西都不一样。 锁看上去生锈了，用石头砸了一下，马上就掉了。 地面立即在您的脚下震动并破裂，强烈的热量击中您的脸，岩浆从核心沸腾。',
    'You can run': '你可以运行',
    'while you wait!': '当你等待时！',
    'Where one minute ago there was dirt, grass, and noxious fog, there are now rivers of molten rock (and noxious fog). You\'d really like to try and repair the planet somehow, so you decide to keep pushing on. It\'s been working out well so far, there was some useful stuff in that chest!': '一分钟前有泥土，草丛和有害雾气的地方，现在有熔岩河（有毒雾气）。 您真的很想尝试以某种方式修复地球，因此您决定继续前进。 到目前为止，效果一直很好，那个箱子里有一些有用的东西！',
    'The heat is tough on your Trimps, causing each Zone to reduce their attack and health by 20% more than the last. 10% of your Nurseries will permanently close after each Zone to avoid Magma flows, and Corruption has seeped into both Void and regular Maps, further increasing their difficulty.': '热浪对您的脆皮不利，导致每个区域的攻击力和生命值都比上一个区域减少20％。 每个区域结束后，您的苗圃中有10％将永久关闭，以避免岩浆流动，并且腐败渗透到了虚空地图和常规地图中，进一步增加了难度。',
    'Though you\'ve seen the Corruption grow since the planet broke, you can now see a giant spire pumping out tons of the purple goo. Things seem to be absorbing it at a higher rate now.': '尽管自从行星破裂以来您已经看到了腐败的增长，但是现在您可以看到一个巨大的尖顶抽出大量的紫色粘胶。 现在看来，事物正在以更高的速度吸收它。',
    'For your past completions of 50 unique Bionic Wonderland Tiers, you have unlocked the following permanent special bonuses: Foremany (Permanently adds 50000 Foreman to your town to aid in construction), AutoJobs, AutoStructure, and Double Build (Stacked items in the Building Queue will be constructed two at a time). As these bonuses were previously Masteries and are now not, new Masteries have been added to replace these!': '对于你过去完成的50个独特的仿生仙境层，你已经解锁了以下永久的特殊奖励:脱颖而出(永久增加50000工头到你的城市，以协助建设)，自动工作, 自动建筑，和双重建造(堆叠项目的建设队列将建设两个一次)。由于这些加值以前是高精而现在不是，新的高精被添加来代替!',
    'A lot of other new stuff has just been added to Trimps as well, click': '脆皮刚刚添加了许多其他新内容，请点击',
    'Bring it on': '来吧',
    'Improbabilities and Void Maps are now more difficult.': '不大可能发生虚空地图现在都比较困难。',
    'Improbabilities and Void Maps now drop 2x helium.': '不可能和虚空图现在会掉落2倍的氦气。',
    'in the bottom right of your game window to see the full patch notes!': '在游戏窗口的右下角，查看完整的补丁说明！',
    'However, the chest contained plans and materials for the': '然而，箱子里装着的计划和材料',
    'The Turkimps escaped again': 'Turkimps又逃跑了',
    'Travel to the Map Chamber. Maps are filled with goodies, and for each max level map you clear you will gain a 20% stacking damage bonus for that Zone (stacks up to 10 times). (Hotkey: M': '去地图室。地图充满了好东西，每清除一张最高等级地图，你将获得该区域20%的堆叠伤害加成(堆叠最多10次)。(热键:M',
    'There\'s a Snimp in the pantry': '储藏室中有一个Snimp',
    'You found 1 map fragments!': '您找到1个地图碎片！',
    'Fluffy wrote a novel while you were gone': '当你不在的时候，蓬松写了一本小说',
    'Your Spire Traps and Towers have also produced': '您的尖顶陷阱和防御塔也已产生',
    '! In addition, all Zones are now wort': '!此外，所有的区域现在都是wort',
    'Runestones while you were away!': '符石在你离开时！',
    'Spire II': '尖塔 II',
    'if your Trimps have a tendency to slack off when you turn your back.': '如果您的脆皮在转身时有放松的趋势。',
    'Hotkeys: S or': '热键：S 或',
    'In addition, having at least one Amalgamator will cause Anticipation stacks to increase based on when the last soldiers were sent, rather than being based on time spent actually breeding.': '此外，至少有一个混血师会导致预期堆叠的增加是基于最后一名士兵被派遣的时间，而不是基于实际繁殖的时间。',
    'MagnetoShriek is NOT active and will not fire.': '磁力护盾未激活，将不会触发。',
    'No Formation': '没有阵型',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '\n								Get one Heirloom at the chances above, based on highest zone\n							': '根据最高区域，在上述机会中获得一件传家宝',
    '\n					You can earn achievements by doing stuff. Each achievement will boost the amount of damage your Trimps can deal, and later achievements grant a larger bonus. You can learn more about an achievement by hovering your mouse over it.': '你可以通过做事来获得成就。每一个成就都将增加你的脆皮所能造成的伤害，之后的成就会给予更多的奖励。你可以通过把鼠标悬停在某项成就上来了解它的更多信息。',
    '\n				Making up lost time...\n			': '弥补失去的时间…',
    '\n								Get one Heirloom at the chances above, based on highest zone\n							': '根据最高区域获得一个传家宝的机会',
    '\n			Heirlooms are powerful items that can drop with a variety of bonuses and a variety of rarities. You will earn one Heirloom every time a Void Map is completed, and you have a better chance to get higher rarities if you complete the Void Map at higher zones. Once you have an Heirloom, you can click the icon below to select it.': '传家宝是强大的物品，可以随着各种奖金和各种稀有物质下降。 每次完成虚空地图时，您将获得一个传家宝，如果您在更高的区域完成虚空地图，您将有更好的机会获得更高的稀有度。 有了传家宝后，您可以点击下面的图标将其选中。',
    '\n			You can only carry a few Heirlooms (other than the two you have equipped) back through the Portal with you when you use it.': '当你使用它时，你只能随身携带几个传家宝（你装备的两个传家宝除外）。',
    'employed\n					': '就业',
    '\n			Once you\'ve selected an Heirloom, you can see all of its stats on the right side of this screen.': '一旦你选中了传家宝，你可以在这个屏幕的右侧看到它的所有统计数据。',
    '\n			You Found an Heirloom!\n\n			': '你找到一件传家宝！',
    '\n				Current Run\n			': '本轮游戏',
    '\n				Total\n			': '总计',
    '| What\'s New \n					': '新东西',
    'Dark Essence\n										': '黑暗精华',
    '\n													Wind\n											': '风',
    '\n												Ice\n											': '冰',
    '\n												Poison									\n											': '毒',
    '\n											Extra Zones\n										': '额外区域',
    '\n											Perfect Sliders\n										': '完美的滑块',
    '\n											Tokens': '符记',
    '\n											Unlock at Z': '解锁于区域',
    '\n										Biome\n									': '生物群',
    '\n										Difficulty\n									': '困难',
    '\n										Loot\n									': '掠夺',
    '\n										Recycle Map\n									': '回收地图',
    '\n										Run Map\n									': '运行地图',
    '\n										Size\n									': '大小',
    '\n										Special Modifier\n									': '特殊修饰符',
    '\n									AutoFight Off\n								': '自动战斗 关闭',
    '\n									Create\n								': '创建',
    '\n									Exit Spire\n								': '退出尖塔',
    '\n									Fight\n								': '战斗',
    '\n									Finish Daily\n								': '完成日常',
    '\n									Level': '等级',
    '\n									Portal\n								': '传送门',
    '\n									Repeat Off\n								': '重复 关闭',
    '\n									Void Maps\n								': '虚空地图',
    '\n								Buy Bone Portal (100 bones)\n							': '购买骨头传送门 (100 骨头)',
    '\n								Buy Heirloom (30 bones)\n							': '购买传家宝 (30 骨头)',
    '\n								Get one Heirloom at the chances above, based on highest zone\n							': '在上面的机会得到一个传家宝，基于最高区域',
    '\n							Equipped Core': '装备核心',
    '\n							Equipped Shield': '装备盾牌',
    '\n							Equipped Staff': '装备棍棒',
    '\n							One of your storage structures will be more expensive than the amount you can receive from this boost. Spend some resources first to get the most benefit!\n						': '您的一个存储结构将比您从此增强中获得的数量更昂贵。 先花一些资源才能获得最大收益！',
    '\n						Bone Trader\n					': '骨法商人',
    '\n						Close\n					': '关闭',
    '\n						Save': '保存',
    '\n						The Bone Trader trades bones for... bonuses\n					': '骨法商人用骨头交换...奖励',
    '\n						You can earn bones as you progress through the world by killing Skeletimps and Megaskeletimps.\n					': '通过杀死骷髅脆皮和Megaskeletimps，你可以在世界进步的过程中获得骨骼。',
    '\n						You have': '你有',
    '\n					Carried': '携带的',
    '\n					Temporary': '临时',


    //阻止页面打印

    '': '',

    //原样
    'Squimp': '鱿鱼',
    'Elephimp': '大象',
    'Chimp': '黑猩猩',
    'Gorillimp': 'Gorillimp',
    'Snimp': 'Snimp',
    'Turtlimp': 'Turtlimp',
    'Skeletimp': '骷髅脆皮',
    'Skeletimps': '骷髅脆皮',
    'Chronoimp': 'Chronoimp',
    'Feyimp': 'Feyimp',
    'Flutimp': 'Flutimp',
    'Jestimp': 'Jestimp',
    'Magnimp': '岩浆脆皮',
    'Tauntimp': 'Tauntimp',
    'Titimp': 'Titimp',
    'Venimp': '吸血鬼脆皮',
    'Whipimp': 'Whipimp',
    'Goblimp': '哥布林脆皮',
    'Blimp': '飞艇',
    'Liquimp': 'Liquimp',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Omnipotrimp': 'Omnipotrimp',
    'Magma Dragimp': '岩浆 Dragimp',
    'Magma Elephimp': '岩浆 Elephimp',
    'Magma Feyimp': '岩浆 Feyimp',
    'Magma Gorillimp': '岩浆 Gorillimp',
    'Magma Liquimp': '岩浆 Liquimp',
    'Magma Magnimp': '岩浆 Magnimp',
    'Magma Omnipotrimp': '岩浆 Omnipotrimp',
    'Magma Penguimp': '岩浆 Penguimp',
    'Magma Randimp': '岩浆 Randimp',
    'Magma Snimp': '岩浆 Snimp',
    'Magma Squimp': '岩浆 Squimp',
    'Magma Tauntimp': '岩浆 Tauntimp',
    'Magma Turkimp': '岩浆 Turkimp',
    'Magma Turtlimp': '岩浆 Turtlimp',
    'Magma Venimp': '岩浆 Venimp',
    'Magma Whipimp': '岩浆 ',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*\-?$/, //12.34e+4
    /^\s*$/, //纯空格
	/^\d+(\.\d+)?(e[+\-]?\d+)?\s*工作空间$/, //12.34e+4
	/^\d+(\.\d+)?(e[+\-]?\d+)?\s*\/秒$/, //12.34e+4
	/^\d+\s*工头$/, //12.34e+4
	/^\d+\s*级地图$/, //12.34e+4
	/^\d+\s*岩浆岩$/, //12.34e+4
	/^\d+\s*Mi$/, //12.34e+4
	/^(\d+\s*分\s*)?\d+\s*秒$/, //12.34e+4
	/^(\d+\s*时\s*)?\d+\s*分$/, //12.34e+4
	/^(\d+\s*天\s*)?\d+\s*时$/, //12.34e+4
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^\n							([\d\.]+) hours\n						$/, '$1 小时'],
    [/^(\d+) Barns, (\d+) Sheds, and (\d+) Forges.$/, '$1个谷仓，$2个棚屋和$3个锻造间。'],
    [/^While you were away, your Trimps were able to produce (.+) food, (.+) wood, (.+) metal, (.+) gems, and (.+) fragments$/, '当您不在时，您的脆皮产生了$1的食物，$2的木材，$3的金属，$4的宝石和$5的碎片'],
    [/^Progress: ([\d\.]+)$/, '进度：$1'],
    [/^Progress: ([\d\.]+) \/$/, '进度：$1'],
    [/^Welcome to ([\d\.]+)$/, '欢迎来到 $1'],
    [/^Welcome to Patch ([\d\.]+)!$/, '欢迎使用$1补丁！'],
    [/^([\d\.]+) Secs$/, '$1 秒'],
    [/^([\d\.]+)\/hr$/, '$1 \/小时'],
    [/^([\d\.]+) Frags$/, '$1 碎片'],
    [/^Find an uncommon heirloom at (.+) or higher$/, '在$1或更高的地方找到罕见的传家宝'],
    [/^(.+) copies of Coordination$/, '$1 份协调'],
    [/^Z (.+) map$/, '区域 $1 地图'],
    [/^You have (.+) Fragments.$/, '您有$1片段。'],
    [/^(.+) Mins (.+) Sec$/, '$1 分 $2 秒'],
    [/^(.+) Day (.+) Hour$/, '$1 天 $2 小时'],
    [/^(.+) Day (.+) Hours$/, '$1 天 $2 小时'],
    [/^(.+) Days (.+) Hours$/, '$1 天 $2 小时'],
    [/^It takes some patience, but you can teach these Trimps to do some research for you. Each Scientist records (.+) units of pure science each second.$/, '这需要一些耐心，但是您可以教这些Trimps为您做一些研究。 每位科学家每秒记录$1单位纯科学。'],
    [/^Train one of your Trimps in the ancient art of farming. Each Farmer harvests (.+) food per second.$/, '在古老的耕作艺术中训练您的脆皮之一。 每个农民每秒收获$1粮食。'],
    [/^Show a Trimp how to cut one of those weird trees down. Each Lumberjack hauls back (.+) logs per second.$/, '向脆皮展示如何砍掉其中一棵怪异的树木。 每个伐木工人每秒钟可拖回$1根原木。'],
    [/^Send your misbehaving Trimps to the mines for some therapeutic work. Each Miner can find and smelt (.+) bars of metal per second.$/, '将行为不端的脆皮送到地雷进行一些治疗工作。 每个矿工每秒可以发现和冶炼$1金属条。'],
    [/^Welcome back! You were offline for (.+) days and (.+) hours.$/, '欢迎回来!你离线$1天$2小时。'],
    [/^Welcome back! You were offline for (.+) minutes and (.+) seconds.$/, '欢迎回来!你离线$1分$2秒。'],
    [/^Welcome back! You were offline for (.+) minutes.$/, '欢迎回来!你离线$1分钟。'],
    [/^(.+) Min (.+) Sec$/, '$1 分 $2 秒'],
    [/^It's kind of heavy for your Trimps, but they'll manage. Adds (.+) attack to each soldier per level$/, '对于您的脆皮来说有点沉重，但他们会设法解决。 每级向每名士兵增加$1攻击'],
    [/^(.+) Level map$/, '$1 级地图'],
    [/^(.+) Secs \/ (.+) Secs$/, '$1 秒 \/ $2 秒'],
    [/^Clear  (.+) total Zones$/, '总共清理 $1 区域'],
    [/^Collect  (.+) Gem$/, '收集 $1 宝石'],
    [/^Drops (.+) Gems$/, '掉落 $1 宝石'],
    [/^food:(.+)\($/, '食物: $1 \('],
    [/^metal:(.+)\($/, '金属: $1 \('],
    [/^wood:(.+)\($/, '木头: $1 \('],
    [/^science:(.+)\($/, '科学: $1 \('],
    [/^([\d\.]+) Trimp$/, '$1 脆皮'],
    [/^([\d\.]+) Trimps$/, '$1 脆皮'],
    [/^(.+) \/ (.+) ticks \($/, '$1 \/ $2 \('],
    [/^(.+) seconds processed in (.+) seconds \((.+) speed$/, '$2秒内处理了$1秒（$3 速度'],
    [/^You have cleared enough land to support (.+) more Trimps!$/, '您已经清理了足够的土地来容纳$1个以上的脆皮！'],
    [/^wood:(.+)\((\d+) Years (\d+) Days$/, '木头：$1 \($2 年 $3 天'],
    [/^food:(.+)\((\d+) Sec$/, '食物：$1 \($2 秒'],
    [/^food:(.+)\((\d+) Secs$/, '食物：$1 \($2 秒'],
    [/^wood:(.+)\((\d+) Secs$/, '木头：$1 \($2 秒'],
    [/^metal:(.+)\((\d+) Secs$/, '金属：$1 \($2 秒'],
    [/^food:(.+)\((\d+) Min (\d+) Sec$/, '食物：$1 \($2 分 $3 秒'],
    [/^food:(.+)\((\d+) Mins (\d+) Secs$/, '食物：$1 \($2 分 $3 秒'],
    [/^food:(.+)\((\d+) Mins (\d+) Sec$/, '食物：$1 \($2 分 $3 秒'],
    [/^food:(.+)\((\d+) Min (\d+) Secs$/, '食物：$1 \($2 分 $3 秒'],
    [/^wood:(.+)\((\d+) Sec$/, '木头：$1 \($2 秒'],
    [/^wood:(.+)\((\d+) Min (\d+) Sec$/, '木头：$1 \($2 分 $3 秒'],
    [/^wood:(.+)\((\d+) Mins (\d+) Secs$/, '木头：$1 \($2 分 $3 秒'],
    [/^wood:(.+)\((\d+) Mins (\d+) Sec$/, '木头：$1 \($2 分 $3 秒'],
    [/^wood:(.+)\((\d+) Min (\d+) Secs$/, '木头：$1 \($2 分 $3 秒'],
    [/^metal:(.+)\((\d+) Mins (\d+) Secs$/, '金属：$1 \($2 分 $3 秒'],
    [/^metal:(.+)\((\d+) Min (\d+) Secs$/, '金属：$1 \($2 分 $3 秒'],
    [/^metal:(.+)\((\d+) Mins (\d+) Sec$/, '金属：$1 \($2 分 $3 秒'],
    [/^Have  (.+) total Trimps$/, '总共拥有 $1 脆皮'],
    [/^Reach (.+) displayed damage$/, '达到 $1 的显示伤害'],
    [/^Check Traps(.+)$/, '检查陷阱$1'],
    [/^\n							Buy (\d+) Hours \((\d+) bones\)\n						$/, '购买 $1 小时 \($2 骨头\)'],
    [/^Min (.+) Max$/, '最小 $1，最高'],
    [/^Respec (.+) bones$/, '恢复 $1 骨头'],
    [/^While you were away, your Trimps were able to produce (.+) wood.$/, '当你离开时，你的脆皮生产了$1种木材。'],
    [/^While you were away, your Trimps were able to produce (.+) food, (.+) wood, (.+) metal, (.+) gems, and (.+) fragments.$/, '当你离开时，你的脆皮生产了$1食物，$2木材，$3金属，$4宝石和$5碎片。'],
    [/^You obliterated a (.+)!$/, '你抹杀了一个 $1!'],
    [/^You vaporized an (.+)!$/, '你汽化了一个 $1!'],
    [/^You slew a (.+)!$/, '你杀害了一个 $1!'],
    [/^You killed a (.+)!$/, '你杀死了一个 $1!'],
    [/^You destroyed a (.+)!$/, '你摧毁了一个 $1!'],
    [/^You ruined a (.+)!$/, '你毁灭了一个 $1!'],
    [/^You ruined an (.+)!$/, '你毁灭了一个 $1!'],
    [/^You extinguished a (.+)!$/, '你灭绝了一个 $1!'],
    [/^You wrecked a (.+)!$/, '你击毁了一个 $1!'],
    [/^You liquidated a (.+)!$/, '你清算了一个 $1!'],
    [/^You demolished a (.+)!$/, '你捣毁了一个 $1!'],
    [/^You just found (.+) bars of metal! Convenient!$/, '你发现了$1金属棒!方便！'],
    [/^You just found (.+) wood! That's pretty neat!$/, '你发现了$1木头!这非常棒!'],
    [/^That guy just left (.+) food on the ground! Sweet!$/, '那家伙刚刚在地上留下了$1的食物！ 甜蜜！'],
    [/^(\d+) workspace$/, '$1 工作空间'],
    [/^(\d+) Mins (\d+) Secs$/, '$1 分 $2 秒'],
    [/^(\d+) Min (\d+) Secs$/, '$1 分 $2 秒'],
    [/^(\d+) Hours (\d+) Mins$/, '$1 时 $2 分'],
    [/^(\d+) Hour (\d+) Mins$/, '$1 时 $2 分'],
    [/^(\d+) Hours (\d+) Min$/, '$1 时 $2 分'],
    [/^(\d+) Hour (\d+) Min$/, '$1 时 $2 分'],
    [/^Trade (.+) Bones$/, '交易 $1 骨头'],
    [/^Trade (.+) Bone$/, '交易 $1 骨头'],
    [/^Spirestones: (.+) \/$/, '尖塔石头: $1 \/'],
    [/^You see (.+) canisters of Helium left on the ground and pick them up. Useful!$/, '你看到$1的氦气罐留在地上并捡起来。 很有用！'],
    [/^(.+) Foremen$/, '$1 工头'],
    [/^(.+) Helium$/, '$1 氦'],
    [/^(.+) Tokens$/, '$1 符记'],
    [/^(.+) damage for (.+) seconds in maps$/, '地图中$2秒造成$1的伤害'],
    [/^(.+) Map Loot$/, '$1 地图掠夺'],
    [/^(.+) Breed Speed$/, '$1 选育速度'],
    [/^- (.+) Seconds$/, '- $1 秒'],
    [/^food: ([\d\.]+) \($/, '食物: $1 \('],
    [/^wood: ([\d\.]+) \($/, '木头: $1 \('],
    [/^(.+) workspaces$/, '$1 工作台'],
    [/^\+([\d\.]+)\% Damage$/, '\+$1\% 伤害'],
    [/^Zone (\d+), Cell$/, '区域 $1, 格子'],
    [/^Golden Battle (.+)$/, '金色战斗 $1'],
    [/^Golden Helium (.+)$/, '金色氦 $1'],
    [/^Golden Void (.+)$/, '金色虚空 $1'],
    [/^Bionic Wonderland (.+)$/, '仿生仙境 $1'],
    [/^Knowledge Tower (.+)$/, '知识塔 $1'],
    [/^Lightning Trap (.+)$/, '闪电陷阱 $1'],
    [/^Frost Trap (.+)$/, '冰霜陷阱 $1'],
    [/^Fire Trap (.+)$/, '火焰陷阱 $1'],
    [/^Poison Trap (.+)$/, '毒药陷阱 $1'],
    [/^Condenser Tower (.+)$/, '冷凝器塔 $1'],
    [/^(.+)\/sec$/, '$1\/秒'],
    [/^(.+) Trimp just ceased to be.$/, '$1个脆皮刚刚终结了。'],
    [/^(.+) Trimp just bit the dust.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just took a dirt nap.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just expired.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just kicked the bucket.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just evaporated.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just needed more armor.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just exploded.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just melted.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just fell over.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just swam the river Styx.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just turned into jerky.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just forgot to put armor on.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just croaked.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just flatlined.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just won't follow you to battle again.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just died. Lame.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just lagged out.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimp just imp-loded.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just ceased to be.$/, '$1个脆皮刚刚终结了。'],
    [/^(.+) Trimps just bit the dust.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just took a dirt nap.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just expired.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just kicked the bucket.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just evaporated.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just needed more armor.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just exploded.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just melted.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just fell over.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just swam the river Styx.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just turned into jerky.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just forgot to put armor on.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just croaked.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just flatlined.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just won't follow you to battle again.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just died. Lame.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just lagged out.$/, '$1个脆皮刚刚阵亡了。'],
    [/^(.+) Trimps just imp-loded.$/, '$1个脆皮刚刚阵亡了。'],
	[/^This book will teach your soldiers how to utilize the buddy system. Fighting will now require (.+) more Trimps \(rounded up\), but attack and health will grow for each new Trimp.$/, '这本书将教你的士兵如何利用伙伴系统。 战斗现在需要$1脆皮（四舍五入），但每个新脆皮的攻击和生命都会增长。'],
	[/^Better than nothing. Adds (.+) attack to each soldier per level$/, '有总比没有好。每级增加攻击力$1'],
	[/^A big, wooden shield. Adds (.+) health to each soldier per level.$/, '一个大大的木质盾牌，每级增加每名士兵$1点生命'],

]);
